project_id = "wxafzwlodzohrwdwkuzy"

[functions.check-overdue-invoices]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.post-daily-room-charges]
verify_jwt = false

[functions.pacs-gateway]
verify_jwt = false

[functions.pacs-settings]
verify_jwt = false
