import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Tables, TablesInsert } from "@/integrations/supabase/types";

export type LabOrder = Tables<"lab_orders">;
export type LabOrderItem = Tables<"lab_order_items">;
export type LabOrderInsert = TablesInsert<"lab_orders">;
export type LabOrderItemInsert = TablesInsert<"lab_order_items">;

export interface LabOrderItemInput {
  service_type_id?: string;
  test_name: string;
  test_category: string;
  instructions?: string;
}

export interface LabOrderWithItems extends LabOrder {
  items?: LabOrderItem[];
  patient?: Tables<"patients">;
  doctor?: Tables<"doctors"> & { profile?: Tables<"profiles"> };
}

interface LabOrderFilters {
  patientId?: string;
  consultationId?: string;
  status?: string;
  branchId?: string;
}

// Fetch lab orders with optional filters
export function useLabOrders(filters: LabOrderFilters = {}) {
  return useQuery({
    queryKey: ["lab-orders", filters],
    queryFn: async () => {
      let query = supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*),
          patient:patients(id, first_name, last_name, patient_number),
          doctor:doctors(id, profile:profiles(full_name))
        `)
        .order("created_at", { ascending: false });

      if (filters.patientId) {
        query = query.eq("patient_id", filters.patientId);
      }
      if (filters.consultationId) {
        query = query.eq("consultation_id", filters.consultationId);
      }
      if (filters.status) {
        query = query.eq("status", filters.status as "ordered" | "collected" | "processing" | "completed" | "cancelled");
      }
      if (filters.branchId) {
        query = query.eq("branch_id", filters.branchId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as LabOrderWithItems[];
    },
  });
}

// Fetch single lab order
export function useLabOrder(id: string | undefined) {
  return useQuery({
    queryKey: ["lab-order", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*),
          patient:patients(id, first_name, last_name, patient_number, date_of_birth, gender),
          doctor:doctors(id, profile:profiles(full_name))
        `)
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as LabOrderWithItems;
    },
    enabled: !!id,
  });
}

// Fetch lab order by consultation
export function useLabOrderByConsultation(consultationId: string | undefined) {
  return useQuery({
    queryKey: ["lab-order-by-consultation", consultationId],
    queryFn: async () => {
      if (!consultationId) return null;
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*)
        `)
        .eq("consultation_id", consultationId)
        .maybeSingle();

      if (error) throw error;
      return data as LabOrderWithItems | null;
    },
    enabled: !!consultationId,
  });
}

// Create lab order with items
export function useCreateLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      labOrder,
      items,
    }: {
      labOrder: {
        consultation_id: string;
        patient_id: string;
        doctor_id: string;
        branch_id: string;
        priority?: "routine" | "urgent" | "stat";
        clinical_notes?: string;
      };
      items: LabOrderItemInput[];
    }) => {
      // Create lab order (order_number auto-generated by trigger)
      const { data: order, error: orderError } = await supabase
        .from("lab_orders")
        .insert({
          order_number: "TEMP", // Will be replaced by trigger
          consultation_id: labOrder.consultation_id,
          patient_id: labOrder.patient_id,
          doctor_id: labOrder.doctor_id,
          branch_id: labOrder.branch_id,
          priority: labOrder.priority || "routine",
          clinical_notes: labOrder.clinical_notes,
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create lab order items
      if (items.length > 0) {
        const itemsToInsert = items.map((item) => ({
          lab_order_id: order.id,
          service_type_id: item.service_type_id || null,
          test_name: item.test_name,
          test_category: item.test_category,
          instructions: item.instructions || null,
        }));

        const { error: itemsError } = await supabase
          .from("lab_order_items")
          .insert(itemsToInsert);

        if (itemsError) throw itemsError;
      }

      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order-by-consultation"] });
    },
  });
}

// Update lab order status
export function useUpdateLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...data
    }: Partial<LabOrder> & { id: string }) => {
      const { data: order, error } = await supabase
        .from("lab_orders")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Fetch patient's lab order history
export function usePatientLabOrders(patientId: string | undefined, limit = 5) {
  return useQuery({
    queryKey: ["patient-lab-orders", patientId, limit],
    queryFn: async () => {
      if (!patientId) return [];
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*)
        `)
        .eq("patient_id", patientId)
        .order("created_at", { ascending: false })
        .limit(limit);

      if (error) throw error;
      return data as LabOrderWithItems[];
    },
    enabled: !!patientId,
  });
}
