import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Tables, TablesInsert } from "@/integrations/supabase/types";
import { labLogger } from "@/lib/logger";

export type LabOrder = Tables<"lab_orders"> & {
  invoice_id?: string | null;
  payment_status?: "pending" | "paid" | "partial" | "waived";
  ordered_by?: string | null;
};
export type LabOrderItem = Tables<"lab_order_items">;
export type LabOrderInsert = TablesInsert<"lab_orders">;
export type LabOrderItemInsert = TablesInsert<"lab_order_items">;

export interface LabOrderItemInput {
  service_type_id?: string;
  test_name: string;
  test_category: string;
  instructions?: string;
  price?: number;
}

export interface LabOrderWithItems extends LabOrder {
  items?: LabOrderItem[];
  patient?: Tables<"patients">;
  doctor?: Tables<"doctors"> & { profile?: Tables<"profiles"> };
  invoice?: Tables<"invoices"> | null;
}

interface LabOrderFilters {
  patientId?: string;
  consultationId?: string;
  surgeryId?: string;
  status?: string;
  branchId?: string;
  paymentStatus?: string;
}

// Fetch lab orders with optional filters
export function useLabOrders(filters: LabOrderFilters = {}) {
  return useQuery({
    queryKey: ["lab-orders", filters],
    queryFn: async () => {
      let query = (supabase as any)
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*),
          patient:patients(id, first_name, last_name, patient_number, date_of_birth, gender, phone),
          doctor:doctors(id, profile:profiles(full_name)),
          invoice:invoices(id, invoice_number, total_amount, paid_amount, status)
        `)
        .order("created_at", { ascending: false });

      if (filters.patientId) {
        query = query.eq("patient_id", filters.patientId);
      }
      if (filters.consultationId) {
        query = query.eq("consultation_id", filters.consultationId);
      }
      if (filters.surgeryId) {
        query = query.eq("surgery_id", filters.surgeryId);
      }
      if (filters.status) {
        query = query.eq("status", filters.status as "ordered" | "collected" | "processing" | "completed" | "cancelled");
      }
      if (filters.branchId) {
        query = query.eq("branch_id", filters.branchId);
      }
      if (filters.paymentStatus) {
        query = query.eq("payment_status", filters.paymentStatus);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as LabOrderWithItems[];
    },
  });
}

// Fetch single lab order with full details
export function useLabOrder(id: string | undefined) {
  return useQuery({
    queryKey: ["lab-order", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*),
          patient:patients(id, first_name, last_name, patient_number, date_of_birth, gender, phone),
          doctor:doctors(id, specialization, qualification, license_number, profile:profiles(full_name))
        `)
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as LabOrderWithItems;
    },
    enabled: !!id,
  });
}

// Fetch lab order by consultation
export function useLabOrderByConsultation(consultationId: string | undefined) {
  return useQuery({
    queryKey: ["lab-order-by-consultation", consultationId],
    queryFn: async () => {
      if (!consultationId) return null;
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*)
        `)
        .eq("consultation_id", consultationId)
        .maybeSingle();

      if (error) throw error;
      return data as LabOrderWithItems | null;
    },
    enabled: !!consultationId,
  });
}

// Create lab order with items and optional invoice
export function useCreateLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      labOrder,
      items,
      createInvoice = false,
      organizationId,
    }: {
      labOrder: {
        consultation_id?: string;
        patient_id: string;
        doctor_id?: string;
        branch_id: string;
        organization_id?: string;
        priority?: "routine" | "urgent" | "stat";
        clinical_notes?: string;
        ordered_by?: string;
      };
      items: LabOrderItemInput[];
      createInvoice?: boolean;
      organizationId?: string;
    }) => {
      labLogger.info("Creating lab order", { 
        consultationId: labOrder.consultation_id,
        patientId: labOrder.patient_id,
        testsCount: items.length,
        priority: labOrder.priority || "routine",
        tests: items.map(i => i.test_name),
        createInvoice
      });

      // Create lab order (order_number auto-generated by trigger)
      const { data: order, error: orderError } = await (supabase as any)
        .from("lab_orders")
        .insert({
          order_number: "TEMP",
          consultation_id: labOrder.consultation_id || null,
          patient_id: labOrder.patient_id,
          doctor_id: labOrder.doctor_id || null,
          branch_id: labOrder.branch_id,
          priority: labOrder.priority || "routine",
          clinical_notes: labOrder.clinical_notes,
          ordered_by: labOrder.ordered_by || null,
          payment_status: "pending",
        })
        .select()
        .single();

      if (orderError) {
        labLogger.error("Failed to create lab order", orderError, { consultationId: labOrder.consultation_id });
        throw orderError;
      }

      // Create lab order items
      if (items.length > 0) {
        const itemsToInsert = items.map((item) => ({
          lab_order_id: order.id,
          service_type_id: item.service_type_id || null,
          test_name: item.test_name,
          test_category: item.test_category,
          instructions: item.instructions || null,
        }));

        const { error: itemsError } = await supabase
          .from("lab_order_items")
          .insert(itemsToInsert);

        if (itemsError) {
          labLogger.error("Failed to create lab order items", itemsError, { orderId: order.id });
          throw itemsError;
        }
      }

      // Create invoice if requested
      let invoice = null;
      if (createInvoice && organizationId && items.length > 0) {
        const today = new Date();
        const dateStr = today.toISOString().slice(0, 10).replace(/-/g, "");
        const randomSuffix = Math.floor(Math.random() * 1000).toString().padStart(3, "0");
        const invoiceNumber = `INV-${dateStr}-${randomSuffix}`;

        const subtotal = items.reduce((sum, item) => sum + (item.price || 0), 0);

        const { data: invoiceData, error: invoiceError } = await supabase
          .from("invoices")
          .insert({
            invoice_number: invoiceNumber,
            patient_id: labOrder.patient_id,
            branch_id: labOrder.branch_id,
            organization_id: organizationId,
            discount_amount: 0,
            tax_amount: 0,
            total_amount: subtotal,
            balance_amount: subtotal,
            paid_amount: 0,
            status: "pending",
            notes: `Invoice for Lab Order ${order.order_number}`,
            created_by: labOrder.ordered_by,
          })
          .select()
          .single();

        if (invoiceError) {
          labLogger.error("Failed to create invoice", invoiceError, { orderId: order.id });
          throw new Error(`Failed to create invoice: ${invoiceError.message}`);
        }
        
        invoice = invoiceData;

        // Create invoice items
        const invoiceItems = items.map((item) => ({
          invoice_id: invoice.id,
          description: item.test_name,
          quantity: 1,
          unit_price: item.price || 0,
          discount_percent: 0,
          total_price: item.price || 0,
          service_type_id: item.service_type_id || null,
        }));

        const { error: invoiceItemsError } = await supabase.from("invoice_items").insert(invoiceItems);
        
        if (invoiceItemsError) {
          labLogger.error("Failed to create invoice items", invoiceItemsError, { invoiceId: invoice.id });
          throw new Error(`Failed to create invoice items: ${invoiceItemsError.message}`);
        }

        // Update lab order with invoice reference
        const { error: linkError } = await (supabase as any)
          .from("lab_orders")
          .update({ invoice_id: invoice.id })
          .eq("id", order.id);
          
        if (linkError) {
          labLogger.error("Failed to link invoice to lab order", linkError, { orderId: order.id, invoiceId: invoice.id });
        }
      }

      labLogger.info("Lab order created", { 
        orderId: order.id,
        orderNumber: order.order_number,
        testsCount: items.length,
        invoiceId: invoice?.id
      });

      return { order, invoice };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order-by-consultation"] });
      queryClient.invalidateQueries({ queryKey: ["invoices"] });
    },
  });
}

// Update lab order payment status
export function useUpdateLabOrderPayment() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      orderId,
      paymentStatus,
      invoiceId,
    }: {
      orderId: string;
      paymentStatus: "pending" | "paid" | "partial" | "waived";
      invoiceId?: string;
    }) => {
      const updateData: Record<string, unknown> = { payment_status: paymentStatus };
      if (invoiceId) updateData.invoice_id = invoiceId;

      const { data, error } = await (supabase as any)
        .from("lab_orders")
        .update(updateData)
        .eq("id", orderId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Update lab order status
export function useUpdateLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...data
    }: Partial<LabOrder> & { id: string }) => {
      const { data: order, error } = await supabase
        .from("lab_orders")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Update lab order item with results
export function useUpdateLabOrderItem() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      result_values,
      result_notes,
      status,
      performed_by,
    }: {
      id: string;
      result_values?: Record<string, string | number>;
      result_notes?: string;
      status?: "pending" | "collected" | "processing" | "completed";
      performed_by?: string;
    }) => {
      const updateData: Record<string, unknown> = {};
      
      if (result_values !== undefined) updateData.result_values = result_values;
      if (result_notes !== undefined) updateData.result_notes = result_notes;
      if (status !== undefined) updateData.status = status;
      if (performed_by !== undefined) updateData.performed_by = performed_by;
      if (status === "completed") updateData.result_date = new Date().toISOString();

      const { data, error } = await supabase
        .from("lab_order_items")
        .update(updateData)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Mark sample as collected with sample number
export function useMarkSampleCollected() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ orderId, sampleNumber }: { orderId: string; sampleNumber: string }) => {
      labLogger.info("Marking sample as collected", { orderId, sampleNumber });

      // Update lab order status and sample number
      const { error: orderError } = await supabase
        .from("lab_orders")
        .update({ 
          status: "collected" as const,
          sample_number: sampleNumber
        })
        .eq("id", orderId);

      if (orderError) {
        labLogger.error("Failed to mark sample collected", orderError, { orderId });
        throw orderError;
      }

      // Update all items to collected
      const { error: itemsError } = await supabase
        .from("lab_order_items")
        .update({ status: "collected" as const })
        .eq("lab_order_id", orderId);

      if (itemsError) {
        labLogger.error("Failed to update lab order items", itemsError, { orderId });
        throw itemsError;
      }

      labLogger.info("Sample collected", { orderId, sampleNumber });

      return true;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Complete lab order (mark all tests as completed)
export function useCompleteLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      orderId,
      result_notes,
    }: {
      orderId: string;
      result_notes?: string;
    }) => {
      labLogger.info("Completing lab order", { orderId });

      const { data, error } = await supabase
        .from("lab_orders")
        .update({
          status: "completed" as const,
          completed_at: new Date().toISOString(),
          result_notes,
        })
        .eq("id", orderId)
        .select()
        .single();

      if (error) {
        labLogger.error("Failed to complete lab order", error, { orderId });
        throw error;
      }

      labLogger.info("Lab order completed", { 
        orderId, 
        orderNumber: data.order_number,
        completedAt: data.completed_at
      });

      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Fetch patient's lab order history
export function usePatientLabOrders(patientId: string | undefined, limit = 5) {
  return useQuery({
    queryKey: ["patient-lab-orders", patientId, limit],
    queryFn: async () => {
      if (!patientId) return [];
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*)
        `)
        .eq("patient_id", patientId)
        .order("created_at", { ascending: false })
        .limit(limit);

      if (error) throw error;
      return data as LabOrderWithItems[];
    },
    enabled: !!patientId,
  });
}
