import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import type { Tables, TablesInsert } from "@/integrations/supabase/types";
import { labLogger } from "@/lib/logger";

export type LabOrder = Tables<"lab_orders">;
export type LabOrderItem = Tables<"lab_order_items">;
export type LabOrderInsert = TablesInsert<"lab_orders">;
export type LabOrderItemInsert = TablesInsert<"lab_order_items">;

export interface LabOrderItemInput {
  service_type_id?: string;
  test_name: string;
  test_category: string;
  instructions?: string;
}

export interface LabOrderWithItems extends LabOrder {
  items?: LabOrderItem[];
  patient?: Tables<"patients">;
  doctor?: Tables<"doctors"> & { profile?: Tables<"profiles"> };
}

interface LabOrderFilters {
  patientId?: string;
  consultationId?: string;
  surgeryId?: string;
  status?: string;
  branchId?: string;
}

// Fetch lab orders with optional filters
export function useLabOrders(filters: LabOrderFilters = {}) {
  return useQuery({
    queryKey: ["lab-orders", filters],
    queryFn: async () => {
      let query = supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*),
          patient:patients(id, first_name, last_name, patient_number, date_of_birth, gender, phone),
          doctor:doctors(id, profile:profiles(full_name))
        `)
        .order("created_at", { ascending: false });

      if (filters.patientId) {
        query = query.eq("patient_id", filters.patientId);
      }
      if (filters.consultationId) {
        query = query.eq("consultation_id", filters.consultationId);
      }
      if (filters.surgeryId) {
        query = query.eq("surgery_id", filters.surgeryId);
      }
      if (filters.status) {
        query = query.eq("status", filters.status as "ordered" | "collected" | "processing" | "completed" | "cancelled");
      }
      if (filters.branchId) {
        query = query.eq("branch_id", filters.branchId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data as LabOrderWithItems[];
    },
  });
}

// Fetch single lab order with full details
export function useLabOrder(id: string | undefined) {
  return useQuery({
    queryKey: ["lab-order", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*),
          patient:patients(id, first_name, last_name, patient_number, date_of_birth, gender, phone),
          doctor:doctors(id, specialization, qualification, license_number, profile:profiles(full_name))
        `)
        .eq("id", id)
        .single();

      if (error) throw error;
      return data as LabOrderWithItems;
    },
    enabled: !!id,
  });
}

// Fetch lab order by consultation
export function useLabOrderByConsultation(consultationId: string | undefined) {
  return useQuery({
    queryKey: ["lab-order-by-consultation", consultationId],
    queryFn: async () => {
      if (!consultationId) return null;
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*)
        `)
        .eq("consultation_id", consultationId)
        .maybeSingle();

      if (error) throw error;
      return data as LabOrderWithItems | null;
    },
    enabled: !!consultationId,
  });
}

// Create lab order with items
export function useCreateLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      labOrder,
      items,
    }: {
      labOrder: {
        consultation_id?: string; // Made optional for direct lab orders
        patient_id: string;
        doctor_id?: string; // Made optional for direct lab orders
        branch_id: string;
        organization_id?: string;
        priority?: "routine" | "urgent" | "stat";
        clinical_notes?: string;
        ordered_by?: string; // Track who created the order
      };
      items: LabOrderItemInput[];
    }) => {
      labLogger.info("Creating lab order", { 
        consultationId: labOrder.consultation_id,
        patientId: labOrder.patient_id,
        testsCount: items.length,
        priority: labOrder.priority || "routine",
        tests: items.map(i => i.test_name)
      });

      // Create lab order (order_number auto-generated by trigger)
      const { data: order, error: orderError } = await supabase
        .from("lab_orders")
        .insert({
          order_number: "TEMP", // Will be replaced by trigger
          consultation_id: labOrder.consultation_id || null,
          patient_id: labOrder.patient_id,
          doctor_id: labOrder.doctor_id || null,
          branch_id: labOrder.branch_id,
          priority: labOrder.priority || "routine",
          clinical_notes: labOrder.clinical_notes,
        })
        .select()
        .single();

      if (orderError) {
        labLogger.error("Failed to create lab order", orderError, { consultationId: labOrder.consultation_id });
        throw orderError;
      }

      // Create lab order items
      if (items.length > 0) {
        const itemsToInsert = items.map((item) => ({
          lab_order_id: order.id,
          service_type_id: item.service_type_id || null,
          test_name: item.test_name,
          test_category: item.test_category,
          instructions: item.instructions || null,
        }));

        const { error: itemsError } = await supabase
          .from("lab_order_items")
          .insert(itemsToInsert);

        if (itemsError) {
          labLogger.error("Failed to create lab order items", itemsError, { orderId: order.id });
          throw itemsError;
        }
      }

      labLogger.info("Lab order created", { 
        orderId: order.id,
        orderNumber: order.order_number,
        testsCount: items.length
      });

      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order-by-consultation"] });
    },
  });
}

// Update lab order status
export function useUpdateLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...data
    }: Partial<LabOrder> & { id: string }) => {
      const { data: order, error } = await supabase
        .from("lab_orders")
        .update(data)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Update lab order item with results
export function useUpdateLabOrderItem() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      result_values,
      result_notes,
      status,
      performed_by,
    }: {
      id: string;
      result_values?: Record<string, string | number>;
      result_notes?: string;
      status?: "pending" | "collected" | "processing" | "completed";
      performed_by?: string;
    }) => {
      const updateData: Record<string, unknown> = {};
      
      if (result_values !== undefined) updateData.result_values = result_values;
      if (result_notes !== undefined) updateData.result_notes = result_notes;
      if (status !== undefined) updateData.status = status;
      if (performed_by !== undefined) updateData.performed_by = performed_by;
      if (status === "completed") updateData.result_date = new Date().toISOString();

      const { data, error } = await supabase
        .from("lab_order_items")
        .update(updateData)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Mark sample as collected with sample number
export function useMarkSampleCollected() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ orderId, sampleNumber }: { orderId: string; sampleNumber: string }) => {
      labLogger.info("Marking sample as collected", { orderId, sampleNumber });

      // Update lab order status and sample number
      const { error: orderError } = await supabase
        .from("lab_orders")
        .update({ 
          status: "collected" as const,
          sample_number: sampleNumber
        })
        .eq("id", orderId);

      if (orderError) {
        labLogger.error("Failed to mark sample collected", orderError, { orderId });
        throw orderError;
      }

      // Update all items to collected
      const { error: itemsError } = await supabase
        .from("lab_order_items")
        .update({ status: "collected" as const })
        .eq("lab_order_id", orderId);

      if (itemsError) {
        labLogger.error("Failed to update lab order items", itemsError, { orderId });
        throw itemsError;
      }

      labLogger.info("Sample collected", { orderId, sampleNumber });

      return true;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Complete lab order (mark all tests as completed)
export function useCompleteLabOrder() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      orderId,
      result_notes,
    }: {
      orderId: string;
      result_notes?: string;
    }) => {
      labLogger.info("Completing lab order", { orderId });

      const { data, error } = await supabase
        .from("lab_orders")
        .update({
          status: "completed" as const,
          completed_at: new Date().toISOString(),
          result_notes,
        })
        .eq("id", orderId)
        .select()
        .single();

      if (error) {
        labLogger.error("Failed to complete lab order", error, { orderId });
        throw error;
      }

      labLogger.info("Lab order completed", { 
        orderId, 
        orderNumber: data.order_number,
        completedAt: data.completed_at
      });

      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["lab-orders"] });
      queryClient.invalidateQueries({ queryKey: ["lab-order"] });
    },
  });
}

// Fetch patient's lab order history
export function usePatientLabOrders(patientId: string | undefined, limit = 5) {
  return useQuery({
    queryKey: ["patient-lab-orders", patientId, limit],
    queryFn: async () => {
      if (!patientId) return [];
      const { data, error } = await supabase
        .from("lab_orders")
        .select(`
          *,
          items:lab_order_items(*)
        `)
        .eq("patient_id", patientId)
        .order("created_at", { ascending: false })
        .limit(limit);

      if (error) throw error;
      return data as LabOrderWithItems[];
    },
    enabled: !!patientId,
  });
}
