import {
  Users, Calendar, Stethoscope, AlertTriangle, Pill, FlaskConical,
  Scissors, BedDouble, Calculator, ShoppingCart, Bot, ShieldAlert,
  Brain, Receipt, TrendingUp, ArrowRight, Package, FileText,
  Droplets, ClipboardCheck, Clock, Layers, Bell, Target, Activity,
  Flag, Rocket, Zap, Building2, Globe
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type PostCategory = "modules" | "ai" | "workflows" | "stats" | "brand";

export interface SocialPost {
  id: number;
  hook: string;
  subtext: string;
  category: PostCategory;
  icon: LucideIcon;
  accentColor: string; // tailwind bg class
  gradientFrom: string;
  gradientTo: string;
  module?: string;
}

export const categoryLabels: Record<PostCategory, string> = {
  modules: "Modules",
  ai: "AI / Tabeebi",
  workflows: "Workflows",
  stats: "Stats",
  brand: "Brand",
};

export const categoryColors: Record<PostCategory, string> = {
  modules: "bg-teal-500",
  ai: "bg-pink-500",
  workflows: "bg-blue-500",
  stats: "bg-amber-500",
  brand: "bg-purple-500",
};

export const socialPosts: SocialPost[] = [
  // ── Module Spotlight (1-10) ──
  {
    id: 1,
    hook: "Still using paper files?",
    subtext: "Register patients in 30 seconds with CNIC auto-fill. Digital records, zero paperwork.",
    category: "modules",
    icon: Users,
    accentColor: "bg-teal-500",
    gradientFrom: "from-teal-600",
    gradientTo: "to-emerald-900",
    module: "Patients",
  },
  {
    id: 2,
    hook: "Your patients hate waiting.",
    subtext: "Show them live token queues on TV displays. Real-time updates, happier patients.",
    category: "modules",
    icon: Calendar,
    accentColor: "bg-sky-500",
    gradientFrom: "from-sky-600",
    gradientTo: "to-blue-900",
    module: "Appointments",
  },
  {
    id: 3,
    hook: "AI pre-screens patients before the doctor walks in.",
    subtext: "Tabeebi collects symptoms, history & vitals — so doctors focus on diagnosis.",
    category: "modules",
    icon: Stethoscope,
    accentColor: "bg-violet-500",
    gradientFrom: "from-violet-600",
    gradientTo: "to-purple-900",
    module: "OPD + Tabeebi",
  },
  {
    id: 4,
    hook: "5-Level triage in seconds.",
    subtext: "Because emergencies can't wait. Color-coded severity, instant prioritization.",
    category: "modules",
    icon: AlertTriangle,
    accentColor: "bg-red-500",
    gradientFrom: "from-red-600",
    gradientTo: "to-rose-900",
    module: "Emergency",
  },
  {
    id: 5,
    hook: "Track every pill, every batch, every expiry.",
    subtext: "Automated inventory, smart reorder alerts, and complete batch traceability.",
    category: "modules",
    icon: Pill,
    accentColor: "bg-green-500",
    gradientFrom: "from-green-600",
    gradientTo: "to-emerald-900",
    module: "Pharmacy",
  },
  {
    id: 6,
    hook: "Lab results in minutes, not days.",
    subtext: "With AI-flagged abnormals, analyzer integration, and instant patient notifications.",
    category: "modules",
    icon: FlaskConical,
    accentColor: "bg-cyan-500",
    gradientFrom: "from-cyan-600",
    gradientTo: "to-teal-900",
    module: "Laboratory",
  },
  {
    id: 7,
    hook: "From surgery scheduling to PACU.",
    subtext: "One seamless OT workflow. Pre-op, intra-op, post-op — all connected.",
    category: "modules",
    icon: Scissors,
    accentColor: "bg-orange-500",
    gradientFrom: "from-orange-600",
    gradientTo: "to-amber-900",
    module: "Operation Theatre",
  },
  {
    id: 8,
    hook: "Admit, treat, discharge, bill.",
    subtext: "IPD without the chaos. Bed management, rounds, nursing stations — unified.",
    category: "modules",
    icon: BedDouble,
    accentColor: "bg-indigo-500",
    gradientFrom: "from-indigo-600",
    gradientTo: "to-blue-900",
    module: "IPD",
  },
  {
    id: 9,
    hook: "Double-entry accounting that posts itself.",
    subtext: "Zero manual journal entries. Every transaction auto-posted to the right ledger.",
    category: "modules",
    icon: Calculator,
    accentColor: "bg-slate-500",
    gradientFrom: "from-slate-600",
    gradientTo: "to-gray-900",
    module: "Accounts",
  },
  {
    id: 10,
    hook: "Requisition to vendor payment.",
    subtext: "Procurement on autopilot. 3-way matching, GRN verification, auto approvals.",
    category: "modules",
    icon: ShoppingCart,
    accentColor: "bg-lime-600",
    gradientFrom: "from-lime-700",
    gradientTo: "to-green-900",
    module: "Procurement",
  },

  // ── AI / Tabeebi (11-15) ──
  {
    id: 11,
    hook: "Meet Tabeebi.",
    subtext: "Your AI doctor that never sleeps. 24/7 symptom assessment, triage & guidance in Urdu & English.",
    category: "ai",
    icon: Bot,
    accentColor: "bg-pink-500",
    gradientFrom: "from-pink-600",
    gradientTo: "to-rose-900",
  },
  {
    id: 12,
    hook: "AI drug interaction alerts could save a life today.",
    subtext: "Real-time checks against the entire prescription. Contraindications flagged before dispensing.",
    category: "ai",
    icon: ShieldAlert,
    accentColor: "bg-red-500",
    gradientFrom: "from-rose-600",
    gradientTo: "to-pink-900",
  },
  {
    id: 13,
    hook: "Tabeebi pre-screens patients.",
    subtext: "So doctors focus on what matters. AI-collected history, vitals summary, and preliminary assessment.",
    category: "ai",
    icon: Brain,
    accentColor: "bg-fuchsia-500",
    gradientFrom: "from-fuchsia-600",
    gradientTo: "to-purple-900",
  },
  {
    id: 14,
    hook: "AI-powered billing codes from diagnosis.",
    subtext: "No more guessing. Automatic ICD-10 and procedure code suggestions from clinical notes.",
    category: "ai",
    icon: Receipt,
    accentColor: "bg-violet-500",
    gradientFrom: "from-violet-600",
    gradientTo: "to-indigo-900",
  },
  {
    id: 15,
    hook: "Predictive analytics that spot trends before you ask.",
    subtext: "Patient flow forecasting, revenue predictions, and resource utilization insights.",
    category: "ai",
    icon: TrendingUp,
    accentColor: "bg-purple-500",
    gradientFrom: "from-purple-600",
    gradientTo: "to-violet-900",
  },

  // ── Workflow / Process (16-20) ──
  {
    id: 16,
    hook: "Walk-in to walkout in 15 minutes.",
    subtext: "Registration → Token → Vitals → Consultation → Prescription → Billing. One flow.",
    category: "workflows",
    icon: ArrowRight,
    accentColor: "bg-blue-500",
    gradientFrom: "from-blue-600",
    gradientTo: "to-indigo-900",
  },
  {
    id: 17,
    hook: "The complete procurement cycle in 6 steps.",
    subtext: "Requisition → Approval → PO → GRN → 3-Way Match → Payment. Fully automated.",
    category: "workflows",
    icon: Package,
    accentColor: "bg-emerald-500",
    gradientFrom: "from-emerald-600",
    gradientTo: "to-teal-900",
  },
  {
    id: 18,
    hook: "How a single prescription flows.",
    subtext: "Doctor prescribes → Pharmacy receives → Stock checked → Dispensed → Billed. Seamlessly.",
    category: "workflows",
    icon: FileText,
    accentColor: "bg-teal-500",
    gradientFrom: "from-teal-600",
    gradientTo: "to-cyan-900",
  },
  {
    id: 19,
    hook: "From blood donor to transfusion.",
    subtext: "Zero errors. Donation → Testing → Cross-match → Issue → Transfusion monitoring.",
    category: "workflows",
    icon: Droplets,
    accentColor: "bg-red-500",
    gradientFrom: "from-red-700",
    gradientTo: "to-rose-900",
  },
  {
    id: 20,
    hook: "Nurse shift handover.",
    subtext: "Nothing falls through the cracks. Vitals, meds, alerts — all handed over digitally.",
    category: "workflows",
    icon: ClipboardCheck,
    accentColor: "bg-sky-500",
    gradientFrom: "from-sky-600",
    gradientTo: "to-blue-900",
  },

  // ── Stats / Impact (21-25) ──
  {
    id: 21,
    hook: "45 min → 15 min",
    subtext: "Average patient visit time with AI pre-screening. That's 3x faster throughput.",
    category: "stats",
    icon: Clock,
    accentColor: "bg-amber-500",
    gradientFrom: "from-amber-600",
    gradientTo: "to-orange-900",
  },
  {
    id: 22,
    hook: "20+ modules. 1 platform. Zero paper.",
    subtext: "Every department connected. Every workflow digitized. One unified system.",
    category: "stats",
    icon: Layers,
    accentColor: "bg-yellow-500",
    gradientFrom: "from-yellow-600",
    gradientTo: "to-amber-900",
  },
  {
    id: 23,
    hook: "40% fewer no-shows.",
    subtext: "With automated SMS reminders, WhatsApp confirmations, and easy rescheduling.",
    category: "stats",
    icon: Bell,
    accentColor: "bg-orange-500",
    gradientFrom: "from-orange-600",
    gradientTo: "to-red-900",
  },
  {
    id: 24,
    hook: "99.5% three-way match accuracy.",
    subtext: "PO vs GRN vs Invoice — automated reconciliation that virtually eliminates errors.",
    category: "stats",
    icon: Target,
    accentColor: "bg-emerald-500",
    gradientFrom: "from-emerald-600",
    gradientTo: "to-green-900",
  },
  {
    id: 25,
    hook: "24/7 operations.",
    subtext: "Because healthcare never stops. Cloud-based, always available, always secure.",
    category: "stats",
    icon: Activity,
    accentColor: "bg-red-500",
    gradientFrom: "from-red-600",
    gradientTo: "to-rose-900",
  },

  // ── Brand / CTA (26-30) ──
  {
    id: 26,
    hook: "AI-Powered Hospital Management System.",
    subtext: "Built for Pakistan. Localized billing, CNIC integration, Urdu support, PKR currency.",
    category: "brand",
    icon: Flag,
    accentColor: "bg-green-600",
    gradientFrom: "from-green-700",
    gradientTo: "to-emerald-900",
  },
  {
    id: 27,
    hook: "The future of healthcare is here.",
    subtext: "Are you ready? AI diagnostics, smart workflows, predictive analytics — all in one platform.",
    category: "brand",
    icon: Rocket,
    accentColor: "bg-purple-500",
    gradientFrom: "from-purple-600",
    gradientTo: "to-indigo-900",
  },
  {
    id: 28,
    hook: "Stop managing chaos.",
    subtext: "Start managing health. HealthOS 24 brings order to every department, every shift, every patient.",
    category: "brand",
    icon: Zap,
    accentColor: "bg-amber-500",
    gradientFrom: "from-amber-500",
    gradientTo: "to-orange-900",
  },
  {
    id: 29,
    hook: "From 5-bed clinic to 500-bed hospital.",
    subtext: "HealthOS scales with you. Multi-branch, multi-role, multi-everything.",
    category: "brand",
    icon: Building2,
    accentColor: "bg-blue-500",
    gradientFrom: "from-blue-600",
    gradientTo: "to-slate-900",
  },
  {
    id: 30,
    hook: "Book your free demo today.",
    subtext: "See how HealthOS 24 can transform your hospital operations. Visit healthos.com",
    category: "brand",
    icon: Globe,
    accentColor: "bg-teal-500",
    gradientFrom: "from-teal-500",
    gradientTo: "to-cyan-900",
  },
];
