-- Seed additional Pakistani hospital services - Part 2: Lab, Room & Other
-- All prices in Pakistani Rupees (Rs.)

INSERT INTO service_types (organization_id, name, category, default_price, is_active)
SELECT o.id, s.name, s.category::service_category, s.default_price, true
FROM organizations o
CROSS JOIN (VALUES
  -- ============ LABORATORY SERVICES ============
  ('Complete Blood Count (CBC)', 'lab', 600),
  ('Hemoglobin (Hb)', 'lab', 200),
  ('ESR', 'lab', 250),
  ('Blood Group & Rh Factor', 'lab', 400),
  ('Platelet Count', 'lab', 350),
  ('PT/INR', 'lab', 800),
  ('APTT', 'lab', 900),
  ('Random Blood Sugar (RBS)', 'lab', 200),
  ('Fasting Blood Sugar (FBS)', 'lab', 200),
  ('HbA1c', 'lab', 1500),
  ('Lipid Profile', 'lab', 1800),
  ('Liver Function Tests (LFT)', 'lab', 2000),
  ('Kidney Function Tests (RFT)', 'lab', 1800),
  ('Uric Acid', 'lab', 400),
  ('Electrolytes (Na, K, Cl)', 'lab', 1200),
  ('Calcium', 'lab', 400),
  ('Magnesium', 'lab', 500),
  ('Thyroid Profile (T3, T4, TSH)', 'lab', 2500),
  ('TSH', 'lab', 1000),
  ('Hepatitis B (HBsAg)', 'lab', 700),
  ('Hepatitis C (Anti-HCV)', 'lab', 800),
  ('HIV Screening', 'lab', 1000),
  ('VDRL (Syphilis)', 'lab', 500),
  ('Dengue NS1', 'lab', 2000),
  ('Dengue IgG/IgM', 'lab', 2500),
  ('Typhoid (Widal Test)', 'lab', 500),
  ('Malaria Parasite (MP)', 'lab', 400),
  ('Urine Complete Examination', 'lab', 300),
  ('Urine Culture & Sensitivity', 'lab', 1500),
  ('Stool Complete Examination', 'lab', 400),
  ('Stool Culture', 'lab', 1500),
  ('Blood Culture', 'lab', 2500),
  ('Pus Culture & Sensitivity', 'lab', 1500),
  ('Sputum Culture', 'lab', 1500),
  ('Cardiac Enzymes (Troponin I)', 'lab', 3000),
  ('Troponin T', 'lab', 2500),
  ('CK-MB', 'lab', 1500),
  ('D-Dimer', 'lab', 3500),
  ('CRP (C-Reactive Protein)', 'lab', 800),
  ('Procalcitonin', 'lab', 5000),
  ('Serum Amylase', 'lab', 800),
  ('Serum Lipase', 'lab', 1000),
  ('Serum Bilirubin', 'lab', 400),
  ('Serum Protein', 'lab', 500),
  ('Serum Albumin', 'lab', 400),
  ('Blood Urea', 'lab', 300),
  ('Serum Creatinine', 'lab', 350),
  ('PSA (Prostate Specific Antigen)', 'lab', 2000),
  ('Vitamin D', 'lab', 2500),
  ('Vitamin B12', 'lab', 2000),
  ('Ferritin', 'lab', 1500),
  ('Iron Studies', 'lab', 2000),

  -- ============ IMAGING SERVICES ============
  ('X-Ray (Single View)', 'procedure', 800),
  ('X-Ray (Two Views)', 'procedure', 1200),
  ('Ultrasound Abdomen', 'procedure', 2500),
  ('Ultrasound Pelvis', 'procedure', 2500),
  ('Obstetric Ultrasound', 'procedure', 3000),
  ('Doppler Ultrasound', 'procedure', 4000),
  ('CT Scan (Plain)', 'procedure', 12000),
  ('CT Scan (With Contrast)', 'procedure', 18000),
  ('MRI (Plain)', 'procedure', 20000),
  ('MRI (With Contrast)', 'procedure', 28000),
  ('Mammography', 'procedure', 5000),

  -- ============ ROOM/BED CHARGES ============
  ('General Ward (per day)', 'room', 3000),
  ('Semi-Private Room (per day)', 'room', 6000),
  ('Private Room (per day)', 'room', 10000),
  ('Deluxe Room (per day)', 'room', 15000),
  ('VIP Suite (per day)', 'room', 25000),
  ('ICU (per day)', 'room', 25000),
  ('CCU (per day)', 'room', 25000),
  ('NICU (per day)', 'room', 20000),
  ('PICU (per day)', 'room', 22000),
  ('HDU (per day)', 'room', 18000),
  ('Labor Room (per day)', 'room', 8000),
  ('Operation Theater (per hour)', 'room', 15000),
  ('Recovery Room (per hour)', 'room', 2000),
  ('Emergency Bed (per day)', 'room', 5000),
  ('Observation Bed (per day)', 'room', 4000),

  -- ============ OTHER/ADMINISTRATIVE SERVICES ============
  ('OPD Registration', 'other', 300),
  ('Emergency Registration', 'other', 500),
  ('IPD Registration/Admission', 'other', 500),
  ('Medical Record Copy', 'other', 200),
  ('Birth Certificate', 'other', 500),
  ('Death Certificate', 'other', 500),
  ('Medical Fitness Certificate', 'other', 1000),
  ('Sick Leave Certificate', 'other', 500),
  ('MLC Report', 'other', 2000),
  ('Discharge Summary Copy', 'other', 300),
  ('Ambulance (Within City)', 'other', 3000),
  ('Ambulance (Inter-City per km)', 'other', 50),
  ('Nursing Care (per day)', 'other', 2000),
  ('Physiotherapy Session', 'other', 1500),
  ('Blood Transfusion Service', 'other', 3000),
  ('Ventilator Support (per day)', 'other', 15000),
  ('Anesthesia Charges', 'other', 20000),
  ('Surgeon Fee (Minor)', 'other', 15000),
  ('Surgeon Fee (Major)', 'other', 50000),
  ('Assistant Surgeon Fee', 'other', 10000)
) AS s(name, category, default_price)
WHERE NOT EXISTS (
  SELECT 1 FROM service_types st 
  WHERE st.organization_id = o.id AND st.name = s.name
);