
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority, is_active) VALUES
('red_flags', 'pre_eclampsia', ARRAY['pre-eclampsia','eclampsia','pregnancy hypertension','proteinuria','headache pregnancy','visual disturbance','hellp'], 'Pre-eclampsia / Eclampsia', E'## Pre-eclampsia Red Flags\n\n**Diagnose if after 20 weeks gestation:**\n- BP ≥140/90 + proteinuria\n- Severe: BP ≥160/110\n\n**Warning symptoms:**\n- Severe headache, visual disturbance\n- Epigastric/RUQ pain\n- Sudden edema (face/hands)\n- Brisk reflexes, clonus\n\n**HELLP syndrome:**\n- Hemolysis, Elevated Liver enzymes, Low Platelets\n\n**Immediate action:**\n- IV magnesium sulfate (4g loading, 1g/hr maintenance)\n- IV labetalol or oral nifedipine for BP\n- Delivery is the definitive treatment\n- Monitor: urine output, reflexes, SpO2\n\n⚠️ **Eclamptic seizure → MgSO4 + emergency delivery**', 'en', 'NICE/WHO', 10, true),

('red_flags', 'addisonian_crisis', ARRAY['addisonian crisis','adrenal crisis','adrenal insufficiency','cortisol','hypotension','hyponatremia','steroid'], 'Addisonian Crisis', E'## Addisonian Crisis Red Flags\n\n**Suspect if:**\n- Known adrenal insufficiency + acute illness\n- Sudden steroid withdrawal\n- Hypotension refractory to fluids\n- Hyponatremia, hyperkalemia\n- Hypoglycemia, confusion\n\n**Triggers:**\n- Infection, surgery, trauma\n- Missed steroid doses\n- Vomiting (cannot absorb oral steroids)\n\n**Immediate action:**\n- IV hydrocortisone 100mg stat\n- IV normal saline bolus (1L over 30-60 min)\n- Check and correct glucose\n- Continue hydrocortisone 50mg IV q6-8h\n- Identify and treat precipitant\n\n⚠️ **Do NOT wait for cortisol results — treat empirically if suspected**', 'en', 'Endocrine Society', 10, true),

('red_flags', 'cauda_equina', ARRAY['cauda equina','back pain','urinary retention','saddle anesthesia','bilateral sciatica','bowel incontinence','red flag back'], 'Cauda Equina Syndrome', E'## Cauda Equina Syndrome Red Flags\n\n**Suspect if back pain with ANY of:**\n- Bilateral sciatica or leg weakness\n- Saddle anesthesia (perineal numbness)\n- Urinary retention or incontinence\n- Fecal incontinence\n- Loss of anal tone\n\n**Key points:**\n- Usually due to large central disc prolapse\n- Surgical emergency — delay = permanent deficit\n\n**Immediate action:**\n- Urgent MRI whole spine\n- Bladder scan (post-void residual)\n- Emergency neurosurgical/spinal referral\n- Surgical decompression within 48 hours\n\n⚠️ **Missed cauda equina = lifelong incontinence and disability**', 'en', 'NICE/Neurosurgical', 10, true),

('red_flags', 'thyroid_storm', ARRAY['thyroid storm','thyrotoxic crisis','hyperthyroid','tachycardia','fever','agitation','thyroid emergency'], 'Thyroid Storm', E'## Thyroid Storm Red Flags\n\n**Suspect if known/suspected hyperthyroidism with:**\n- Fever >38.5°C\n- Tachycardia >140 bpm, AF\n- Agitation, confusion, psychosis\n- Heart failure, GI symptoms\n- Burch-Wartofsky score >45\n\n**Immediate action:**\n- Propranolol 60-80mg PO or 1mg IV slowly\n- Propylthiouracil 200mg PO q4h (or carbimazole)\n- Lugol''s iodine 1 hour AFTER PTU\n- IV hydrocortisone 100mg q8h\n- Cooling measures (paracetamol, NOT aspirin)\n- ICU admission\n\n⚠️ **Mortality 10-30% even with treatment — ICU mandatory**', 'en', 'ATA/Endocrine', 10, true),

('red_flags', 'acute_pancreatitis', ARRAY['pancreatitis','epigastric pain','amylase','lipase','gallstones','alcohol','nausea vomiting'], 'Acute Pancreatitis', E'## Acute Pancreatitis Red Flags\n\n**Diagnose if 2 of 3:**\n- Epigastric pain radiating to back\n- Serum amylase/lipase >3x upper normal\n- CT findings of pancreatitis\n\n**Severity markers (poor prognosis):**\n- CRP >150 at 48h\n- APACHE II >8, Glasgow score ≥3\n- Organ failure (renal, respiratory, cardiovascular)\n\n**Common causes:** Gallstones (GET), Ethanol, Trauma, Steroids, Mumps, Autoimmune, Scorpion sting, Hyperlipidemia, ERCP, Drugs\n\n**Management:**\n- Aggressive IV fluids (250-500mL/hr initially)\n- Analgesia (IV paracetamol, opioids if needed)\n- NPO initially, early enteral nutrition\n- ERCP within 24h if biliary obstruction\n\n⚠️ **Necrotizing pancreatitis → ICU, consider antibiotics if infected necrosis**', 'en', 'ACG/WHO', 10, true),

('red_flags', 'postpartum_hemorrhage', ARRAY['postpartum hemorrhage','pph','bleeding after delivery','uterine atony','retained placenta','blood loss'], 'Postpartum Hemorrhage', E'## Postpartum Hemorrhage Red Flags\n\n**Definition:** Blood loss ≥500mL (vaginal) or ≥1000mL (cesarean)\n\n**Causes (4 T''s):**\n- **T**one: uterine atony (most common, 70%)\n- **T**rauma: genital tract tears\n- **T**issue: retained placenta/clots\n- **T**hrombin: coagulopathy\n\n**Immediate action:**\n1. Rub up a contraction (uterine massage)\n2. IV oxytocin 40 units in 500mL over 4h\n3. IM ergometrine 0.5mg (avoid if hypertensive)\n4. Misoprostol 800mcg sublingual\n5. IV tranexamic acid 1g\n6. Bimanual uterine compression\n7. If medical fails → surgical (B-Lynch, balloon, hysterectomy)\n\n⚠️ **PPH is the leading cause of maternal death worldwide**', 'en', 'WHO/RCOG', 10, true),

('red_flags', 'pulmonary_edema', ARRAY['pulmonary edema','flash pulmonary edema','heart failure','dyspnea','orthopnea','pink frothy sputum','crackles'], 'Acute Pulmonary Edema', E'## Acute Pulmonary Edema Red Flags\n\n**Clinical features:**\n- Severe dyspnea, orthopnea\n- Pink frothy sputum\n- Bilateral crackles\n- Tachycardia, hypertension or hypotension\n- SpO2 dropping rapidly\n\n**Immediate action:**\n1. Sit patient upright\n2. High-flow oxygen (target SpO2 >94%)\n3. IV furosemide 40-80mg\n4. GTN infusion (if SBP >90)\n5. CPAP/BiPAP if available\n6. IV morphine 2.5-5mg (with caution)\n7. Identify and treat cause (MI, arrhythmia, fluid overload)\n\n⚠️ **Cardiogenic shock (SBP <90) → inotropes, avoid GTN**', 'en', 'ESC/NICE', 10, true),

('red_flags', 'bowel_obstruction', ARRAY['bowel obstruction','intestinal obstruction','vomiting','constipation','distension','absent bowel sounds','colicky pain'], 'Bowel Obstruction', E'## Bowel Obstruction Red Flags\n\n**Classic features:**\n- Colicky abdominal pain\n- Vomiting (early in small bowel, late in large bowel)\n- Abdominal distension\n- Absolute constipation (no flatus or stool)\n\n**Strangulation signs (surgical emergency):**\n- Constant (not colicky) pain\n- Peritonism, fever\n- Tachycardia, elevated lactate\n\n**Immediate action:**\n- NG tube (drip and suck)\n- IV fluids, correct electrolytes\n- Urinary catheter, strict I/O\n- Abdominal X-ray (dilated loops, air-fluid levels)\n- CT abdomen if diagnosis unclear\n- Surgical review — especially if signs of strangulation\n\n⚠️ **Strangulated bowel = dead bowel → emergency laparotomy**', 'en', 'Surgical/NICE', 10, true),

('red_flags', 'gi_bleed', ARRAY['gi bleed','hematemesis','melena','blood in stool','upper gi bleed','lower gi bleed','vomiting blood','black stool'], 'GI Bleeding', E'## GI Bleeding Red Flags\n\n**Upper GI (hematemesis, melena):**\n- Rockall score for risk stratification\n- Common causes: peptic ulcer, varices, Mallory-Weiss\n\n**Lower GI (hematochezia):**\n- Diverticular, angiodysplasia, colorectal cancer\n\n**Massive bleed signs:**\n- Tachycardia >100, SBP <100\n- Postural drop, pallor, confusion\n- Hemoglobin drop >2g/dL\n\n**Immediate action:**\n1. 2x large bore IV cannula\n2. Crossmatch 4-6 units\n3. IV fluid resuscitation\n4. PPI infusion (omeprazole 80mg bolus then 8mg/hr)\n5. Urgent endoscopy within 24h (within 2h if variceal)\n6. Terlipressin if variceal bleed suspected\n\n⚠️ **Variceal bleed — mortality 20% per episode**', 'en', 'BSG/NICE', 10, true),

('red_flags', 'severe_burns', ARRAY['burns','scalds','thermal injury','chemical burn','inhalation injury','rule of nines','fluid resuscitation'], 'Severe Burns', E'## Severe Burns Red Flags\n\n**Refer to burns unit if:**\n- >10% TBSA (adult), >5% (child)\n- Full thickness burns\n- Face, hands, feet, genitalia, joints\n- Circumferential burns\n- Inhalation injury\n- Chemical or electrical burns\n\n**Assessment:**\n- Rule of Nines (adult) or Lund-Browder (child)\n- Depth: superficial, partial, full thickness\n\n**Fluid resuscitation (Parkland formula):**\n- 4mL × kg × %TBSA in first 24h\n- Half in first 8 hours, half in next 16 hours\n- Ringer''s lactate preferred\n\n**Immediate:**\n- Cool with running water 20 min\n- Cling film cover (not circumferential)\n- Analgesia, tetanus prophylaxis\n\n⚠️ **Inhalation injury: singed nasal hair, stridor → early intubation**', 'en', 'WHO/NICE', 10, true),

('drug_reference', 'metformin', ARRAY['metformin','glucophage','diabetes','blood sugar','type 2 diabetes','oral hypoglycemic','biguanide'], 'Metformin', E'## Metformin (Glucophage)\n\n**Class:** Biguanide\n**Indication:** Type 2 Diabetes (first-line)\n\n**Dosing:**\n- Start: 500mg once daily with food\n- Titrate: increase by 500mg every 1-2 weeks\n- Max: 2000-2550mg/day in divided doses\n- Extended-release available for GI tolerance\n\n**Key points:**\n- Does NOT cause hypoglycemia as monotherapy\n- Weight neutral or slight weight loss\n- Reduces cardiovascular events\n- Take with meals to reduce GI side effects\n\n**Contraindications:**\n- eGFR <30 (stop), reduce dose if 30-45\n- Acute kidney injury\n- Severe liver disease\n- Before contrast dye (hold 48h)\n\n**Side effects:** Nausea, diarrhea, B12 deficiency (long-term)\n\n⚠️ **Lactic acidosis rare but serious — stop if acutely unwell**', 'en', 'BNF/ADA', 7, true),

('drug_reference', 'amlodipine', ARRAY['amlodipine','norvasc','calcium channel blocker','hypertension','blood pressure','ccb','angina'], 'Amlodipine', E'## Amlodipine (Norvasc)\n\n**Class:** Dihydropyridine Calcium Channel Blocker\n**Indications:** Hypertension, stable angina\n\n**Dosing:**\n- Start: 5mg once daily\n- Max: 10mg once daily\n- Elderly: start 2.5mg\n\n**Key points:**\n- Long-acting, once daily dosing\n- Can be used in pregnancy (limited data)\n- Safe in renal impairment\n- Effective in isolated systolic hypertension\n\n**Contraindications:**\n- Cardiogenic shock\n- Severe aortic stenosis\n- Unstable angina (use with caution)\n\n**Side effects:**\n- Ankle edema (dose-dependent, common)\n- Flushing, headache\n- Gum hyperplasia (rare)\n- Dizziness\n\n**Interactions:** Simvastatin (max 20mg with amlodipine), grapefruit juice', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'losartan', ARRAY['losartan','cozaar','arb','angiotensin receptor blocker','hypertension','blood pressure','renal protection'], 'Losartan', E'## Losartan (Cozaar)\n\n**Class:** Angiotensin II Receptor Blocker (ARB)\n**Indications:** Hypertension, diabetic nephropathy, heart failure (if ACEi intolerant)\n\n**Dosing:**\n- Hypertension: 50mg once daily (max 100mg)\n- Heart failure: start 12.5mg, titrate to 150mg\n- Renal protection: 50-100mg daily\n\n**Key points:**\n- ACEi alternative (no cough side effect)\n- Renoprotective in diabetic nephropathy\n- Uricosuric effect (lowers uric acid)\n\n**Contraindications:**\n- Pregnancy (teratogenic) — all trimesters\n- Bilateral renal artery stenosis\n- Hyperkalemia (K+ >5.5)\n\n**Monitoring:**\n- Renal function + K+ at baseline and 1-2 weeks after starting\n- Recheck after dose changes\n\n**Side effects:** Dizziness, hyperkalemia, angioedema (rare)', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'atorvastatin', ARRAY['atorvastatin','lipitor','statin','cholesterol','ldl','cardiovascular','hyperlipidemia'], 'Atorvastatin', E'## Atorvastatin (Lipitor)\n\n**Class:** HMG-CoA Reductase Inhibitor (Statin)\n**Indications:** Hypercholesterolemia, cardiovascular risk reduction\n\n**Dosing:**\n- Primary prevention: 20mg once daily\n- Secondary prevention (post-MI/stroke): 80mg once daily\n- Range: 10-80mg once daily\n- Take at any time (long half-life)\n\n**Key points:**\n- Most potent commonly used statin\n- Reduces LDL by 30-50%\n- Reduces cardiovascular events by 25-35%\n\n**Contraindications:**\n- Active liver disease, unexplained elevated transaminases\n- Pregnancy, breastfeeding\n\n**Monitoring:**\n- LFTs at baseline and 3 months\n- Lipid profile at 3 months\n- CK if muscle symptoms develop\n\n**Side effects:** Myalgia (5-10%), elevated LFTs, rhabdomyolysis (rare)\n\n⚠️ **Stop if CK >10x ULN or severe muscle pain**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'metoprolol', ARRAY['metoprolol','lopressor','betaloc','beta blocker','heart rate','hypertension','angina','heart failure'], 'Metoprolol', E'## Metoprolol (Lopressor/Betaloc)\n\n**Class:** Selective β1 Beta-Blocker\n**Indications:** Hypertension, angina, heart failure, rate control in AF, post-MI\n\n**Dosing:**\n- Hypertension: 50-100mg BD (or 100-200mg SR once daily)\n- Heart failure: start 12.5-25mg BD, titrate slowly\n- Rate control: 25-100mg BD\n\n**Key points:**\n- Cardioselective — safer in mild asthma than non-selective\n- Reduces mortality post-MI\n- Do NOT stop abruptly (rebound tachycardia)\n\n**Contraindications:**\n- Asthma (severe), COPD (severe)\n- Heart block (2nd/3rd degree)\n- Decompensated heart failure\n- Bradycardia <50 bpm\n\n**Side effects:**\n- Fatigue, cold extremities\n- Bradycardia, hypotension\n- Bronchospasm, erectile dysfunction\n- Mask hypoglycemia symptoms in diabetics', 'en', 'BNF/ESC', 7, true),

('drug_reference', 'salbutamol', ARRAY['salbutamol','ventolin','inhaler','asthma','bronchodilator','wheeze','beta2 agonist','reliever'], 'Salbutamol Inhaler', E'## Salbutamol (Ventolin) Inhaler\n\n**Class:** Short-Acting β2 Agonist (SABA)\n**Indications:** Asthma relief, COPD, bronchospasm\n\n**Dosing:**\n- MDI: 100-200mcg (1-2 puffs) PRN, max 8 puffs/day\n- Nebulizer: 2.5-5mg PRN (acute exacerbation)\n- Via spacer: 4-10 puffs (acute, 1 puff at a time)\n\n**Key points:**\n- RELIEVER only — not for regular use\n- Using >3x/week = poorly controlled asthma\n- Always use with spacer for MDI\n- Onset: 1-5 minutes, duration: 4-6 hours\n\n**Side effects:**\n- Tremor, tachycardia, palpitations\n- Hypokalemia (high doses/nebulizer)\n- Headache, muscle cramps\n\n**Red flag:** Needing reliever >3 days/week → step up controller therapy\n\n⚠️ **Overuse without controller = increased asthma mortality risk**', 'en', 'BTS/GINA', 7, true),

('drug_reference', 'prednisolone', ARRAY['prednisolone','prednisone','steroid','corticosteroid','anti-inflammatory','asthma','autoimmune'], 'Prednisolone', E'## Prednisolone\n\n**Class:** Systemic Corticosteroid\n**Indications:** Asthma exacerbation, COPD, autoimmune conditions, allergic reactions\n\n**Dosing:**\n- Asthma exacerbation (adult): 40-50mg daily for 5-7 days\n- Asthma exacerbation (child): 1-2mg/kg/day (max 40mg) for 3-5 days\n- COPD exacerbation: 30mg daily for 5 days\n- Tapering required if >3 weeks of use\n\n**Key points:**\n- Take in morning with food\n- Short courses (<3 weeks) can stop abruptly\n- Carry steroid card if long-term use\n- Sick-day rules: double dose during illness\n\n**Side effects (long-term):**\n- Weight gain, Cushingoid features\n- Osteoporosis, diabetes\n- Adrenal suppression\n- Gastric ulceration, mood changes\n- Immunosuppression, cataracts\n\n⚠️ **Never stop long-term steroids abruptly — risk of Addisonian crisis**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'amoxicillin', ARRAY['amoxicillin','amoxil','antibiotic','penicillin','infection','uti','chest infection','otitis'], 'Amoxicillin', E'## Amoxicillin (Amoxil)\n\n**Class:** Aminopenicillin (β-lactam antibiotic)\n**Indications:** Respiratory tract infections, UTI, otitis media, H. pylori, dental infections\n\n**Dosing (adult):**\n- Standard: 500mg TDS for 5-7 days\n- High dose: 1g TDS (pneumonia)\n- Child: 25-50mg/kg/day in 3 divided doses\n- H. pylori: 1g BD (with PPI + clarithromycin)\n\n**Key points:**\n- Well absorbed orally\n- Safe in pregnancy (Category B)\n- Complete the full course\n\n**Contraindications:**\n- Penicillin allergy (anaphylaxis history)\n- EBV/glandular fever (causes rash — not true allergy)\n\n**Side effects:**\n- Diarrhea, nausea\n- Rash (especially with EBV)\n- Candidiasis\n- Anaphylaxis (rare)\n\n**Interactions:** Warfarin (increased INR), methotrexate (reduced excretion)', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'azithromycin', ARRAY['azithromycin','zithromax','z-pack','macrolide','antibiotic','pneumonia','chlamydia','sinusitis'], 'Azithromycin', E'## Azithromycin (Zithromax)\n\n**Class:** Macrolide Antibiotic\n**Indications:** Community-acquired pneumonia, sinusitis, chlamydia, typhoid, traveler''s diarrhea\n\n**Dosing:**\n- Standard: 500mg day 1, then 250mg days 2-5\n- Chlamydia: 1g single dose\n- Typhoid: 500mg daily for 7 days\n- Child: 10mg/kg day 1, then 5mg/kg days 2-5\n\n**Key points:**\n- Long tissue half-life (continues working 5 days after last dose)\n- Take 1 hour before or 2 hours after meals\n- Alternative for penicillin-allergic patients\n\n**Contraindications:**\n- QT prolongation, concurrent QT-prolonging drugs\n- Severe liver disease\n\n**Side effects:**\n- Nausea, diarrhea, abdominal pain\n- QT prolongation (rare but serious)\n- Hepatotoxicity (rare)\n\n⚠️ **Check QTc if using with other QT-prolonging medications**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'ciprofloxacin', ARRAY['ciprofloxacin','cipro','fluoroquinolone','antibiotic','uti','gastroenteritis','quinolone'], 'Ciprofloxacin', E'## Ciprofloxacin (Cipro)\n\n**Class:** Fluoroquinolone Antibiotic\n**Indications:** UTI, gastroenteritis, bone/joint infections, pseudomonal infections\n\n**Dosing:**\n- UTI: 250-500mg BD for 3-7 days\n- Complicated UTI: 500mg BD for 7-14 days\n- Gastroenteritis: 500mg BD for 3-5 days\n- IV: 400mg BD\n\n**Key points:**\n- Broad-spectrum, good oral bioavailability\n- Avoid in children/adolescents (cartilage damage)\n- NOT first-line for simple UTI (resistance)\n\n**Contraindications:**\n- Pregnancy, breastfeeding\n- Children <18 (relative)\n- Epilepsy (lowers seizure threshold)\n- Tendon disorders, concurrent steroids\n\n**Side effects:**\n- Tendon rupture (especially Achilles)\n- Nausea, diarrhea\n- CNS effects (dizziness, confusion)\n- QT prolongation\n- C. difficile risk\n\n⚠️ **FDA black box warning: tendonitis, neuropathy, CNS effects**', 'en', 'BNF/FDA', 7, true);
