
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority, is_active) VALUES
('drug_reference', 'metronidazole', ARRAY['metronidazole','flagyl','antibiotic','anaerobic','infection','dental','giardia','c diff','trichomoniasis'], 'Metronidazole', E'## Metronidazole (Flagyl)\n\n**Class:** Nitroimidazole (anti-anaerobic/antiprotozoal)\n**Indications:** Anaerobic infections, C. difficile, giardia, H. pylori, dental abscess, trichomoniasis\n\n**Dosing:**\n- Anaerobic infection: 400mg TDS for 7 days\n- C. difficile: 400mg TDS for 10-14 days\n- Giardia: 400mg TDS for 5 days\n- Dental abscess: 200-400mg TDS for 5 days\n\n**Key points:**\n- Excellent anaerobic coverage\n- Crosses blood-brain barrier\n- **AVOID alcohol** (disulfiram-like reaction)\n\n**Contraindications:**\n- Alcohol use during + 48h after treatment\n- First trimester pregnancy (relative)\n\n**Side effects:** Nausea, metallic taste, peripheral neuropathy (prolonged use), dark urine\n\n⚠️ **Disulfiram reaction with alcohol: severe nausea, flushing, tachycardia**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'fluoxetine', ARRAY['fluoxetine','prozac','ssri','depression','antidepressant','anxiety','ocd','bulimia'], 'Fluoxetine', E'## Fluoxetine (Prozac)\n\n**Class:** SSRI (Selective Serotonin Reuptake Inhibitor)\n**Indications:** Major depression, OCD, bulimia nervosa, panic disorder\n\n**Dosing:**\n- Depression: 20mg once daily (morning)\n- OCD: 20-60mg daily\n- Bulimia: 60mg daily\n- Max: 80mg/day\n\n**Key points:**\n- First-line antidepressant\n- Takes 4-6 weeks for full effect\n- Long half-life (good for poor compliance)\n- Can be used in adolescents (preferred SSRI)\n\n**Black box warning:** Suicidality risk in under-25s — monitor closely first 4 weeks\n\n**Contraindications:** Concurrent MAOIs (14-day washout)\n\n**Side effects:** Nausea, insomnia, headache, sexual dysfunction, anxiety (initial), weight changes\n\n⚠️ **Serotonin syndrome risk if combined with MAOIs, tramadol, triptans**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'diazepam', ARRAY['diazepam','valium','benzodiazepine','anxiety','seizure','muscle spasm','sedation','status epilepticus'], 'Diazepam', E'## Diazepam (Valium)\n\n**Class:** Benzodiazepine\n**Indications:** Anxiety, seizures (status epilepticus), muscle spasm, alcohol withdrawal, procedural sedation\n\n**Dosing:**\n- Anxiety: 2-10mg BD-TDS (short-term only)\n- Status epilepticus: 10mg rectal or 10mg IV (slow)\n- Muscle spasm: 5-15mg daily\n- Alcohol withdrawal: 10-20mg, reducing regimen\n\n**Key points:**\n- Long-acting (half-life 20-100 hours)\n- HIGH addiction potential — max 2-4 weeks use\n- Do NOT prescribe long-term for anxiety\n- Flumazenil is the reversal agent\n\n**Contraindications:**\n- Respiratory depression, sleep apnea\n- Myasthenia gravis, severe liver disease\n\n**Side effects:** Drowsiness, confusion (elderly), ataxia, dependence, paradoxical agitation\n\n⚠️ **Respiratory depression risk with opioids — avoid combination**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'insulin', ARRAY['insulin','novorapid','lantus','humalog','diabetes','type 1','injection','rapid acting','long acting','basal bolus'], 'Insulin (Rapid & Long-Acting)', E'## Insulin\n\n**Rapid-acting (NovoRapid/Humalog):**\n- Onset: 10-15 min, peak: 1-2h, duration: 3-5h\n- Give immediately before meals\n- Dose: based on carb counting or sliding scale\n\n**Long-acting (Lantus/Levemir):**\n- Onset: 1-2h, no peak (flat profile), duration: 20-24h\n- Give at same time daily\n- Lantus: once daily, Levemir: once or twice daily\n\n**Basal-bolus regimen:**\n- Basal: 40-50% of total daily dose\n- Bolus: divided across meals\n- Total: ~0.5-1 unit/kg/day\n\n**Storage:** Refrigerate unopened; room temp once opened (28 days)\n\n**Hypoglycemia management:**\n- Mild: 15g fast glucose, recheck 15 min\n- Severe: IM glucagon 1mg or IV dextrose 50%\n\n⚠️ **Never omit basal insulin in Type 1 — risk of DKA**', 'en', 'ADA/BNF', 7, true),

('drug_reference', 'warfarin', ARRAY['warfarin','coumadin','anticoagulant','inr','blood thinner','dvt','pe','atrial fibrillation','vitamin k'], 'Warfarin', E'## Warfarin (Coumadin)\n\n**Class:** Vitamin K Antagonist\n**Indications:** AF, DVT/PE treatment/prevention, mechanical heart valves\n\n**Dosing:**\n- Loading: various protocols (5mg or 10mg start)\n- Maintenance: 1-10mg daily (highly variable)\n- Target INR: 2-3 (most indications), 2.5-3.5 (mechanical valves)\n\n**Key points:**\n- Monitor INR regularly (at least monthly when stable)\n- Many drug and food interactions\n- Vitamin K-rich foods affect levels (consistent intake)\n- Takes 3-5 days for full effect\n\n**Reversal:**\n- Minor bleeding: withhold, oral vitamin K 1-5mg\n- Major bleeding: IV vitamin K 5-10mg + PCC or FFP\n\n**Contraindications:** Pregnancy (teratogenic), active bleeding, severe liver disease\n\n**Interactions:** NSAIDs, antibiotics (clarithromycin, metronidazole), cranberry juice\n\n⚠️ **INR >5 without bleeding → hold warfarin + vitamin K 1-2mg PO**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'aspirin_therapeutic', ARRAY['aspirin','acetylsalicylic acid','antiplatelet','mi','stroke prevention','cardiovascular','blood thinner'], 'Aspirin (Therapeutic)', E'## Aspirin (Acetylsalicylic Acid)\n\n**Indications:**\n- Acute MI: 300mg chewed stat\n- Secondary prevention (post-MI/stroke): 75mg daily\n- Acute ischemic stroke: 300mg daily for 2 weeks\n\n**Dosing:**\n- Antiplatelet: 75-150mg once daily\n- Acute coronary syndrome: 300mg loading\n- Analgesia: 300-900mg every 4-6h (max 4g/day)\n\n**Key points:**\n- Irreversible COX inhibitor\n- Antiplatelet effect lasts 7-10 days\n- Stop 7 days before surgery\n- Gastroprotective agent if high GI risk\n\n**Contraindications:**\n- Children <16 (Reye''s syndrome)\n- Active peptic ulcer, bleeding disorders\n- Aspirin-sensitive asthma\n\n**Side effects:** GI bleeding, dyspepsia, tinnitus (high dose), bronchospasm\n\n⚠️ **Never give aspirin to children with viral illness — Reye''s syndrome risk**', 'en', 'BNF/AHA', 7, true),

('drug_reference', 'diclofenac', ARRAY['diclofenac','voltaren','nsaid','pain','inflammation','arthritis','musculoskeletal','anti-inflammatory'], 'Diclofenac', E'## Diclofenac (Voltaren)\n\n**Class:** NSAID\n**Indications:** Musculoskeletal pain, arthritis, renal colic, dysmenorrhea, post-operative pain\n\n**Dosing:**\n- Oral: 50mg BD-TDS (max 150mg/day)\n- IM: 75mg deep IM (max 2 days)\n- Topical gel: apply 2-4g to affected area TDS-QDS\n- Suppository: 100mg at night\n\n**Key points:**\n- More cardiovascular risk than naproxen\n- Use lowest dose for shortest time\n- Topical form has fewer systemic effects\n\n**Contraindications:**\n- Active GI bleeding/ulcer\n- Severe heart failure, IHD, CVD\n- Severe renal/hepatic impairment\n- Third trimester pregnancy\n- Post-CABG surgery\n\n**Side effects:** GI upset, GI bleeding, renal impairment, fluid retention, cardiovascular events\n\n⚠️ **Avoid in elderly >65 if possible — high GI and renal risk**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'tramadol', ARRAY['tramadol','tramal','opioid','pain','moderate pain','analgesic','controlled'], 'Tramadol', E'## Tramadol (Tramal)\n\n**Class:** Weak Opioid Analgesic (+ SNRI activity)\n**Indications:** Moderate to severe pain\n\n**Dosing:**\n- Oral: 50-100mg every 4-6 hours (max 400mg/day)\n- Elderly: max 300mg/day\n- SR formulations: 100-200mg BD\n\n**Key points:**\n- Step 2 analgesic (WHO pain ladder)\n- Dual mechanism: μ-opioid + serotonin/norepinephrine\n- Lower respiratory depression than strong opioids\n- Still causes dependence — use cautiously\n\n**Contraindications:**\n- Epilepsy (lowers seizure threshold)\n- Concurrent MAOIs/SSRIs (serotonin syndrome risk)\n- Severe respiratory depression\n\n**Side effects:**\n- Nausea, dizziness, constipation\n- Seizures (dose-dependent)\n- Serotonin syndrome (with SSRIs)\n- Dependence and withdrawal\n\n⚠️ **Serotonin syndrome risk — avoid with SSRIs/SNRIs if possible**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'doxycycline', ARRAY['doxycycline','tetracycline','antibiotic','acne','malaria prophylaxis','chlamydia','lyme','respiratory'], 'Doxycycline', E'## Doxycycline\n\n**Class:** Tetracycline Antibiotic\n**Indications:** Acne, chlamydia, COPD exacerbation, Lyme disease, malaria prophylaxis, PID\n\n**Dosing:**\n- Standard: 100mg BD for 7 days (then 100mg OD)\n- Chlamydia: 100mg BD for 7 days\n- Acne: 100mg OD for 6-12 weeks\n- Malaria prophylaxis: 100mg OD (start 2 days before, continue 4 weeks after)\n\n**Key points:**\n- Take with food and plenty of water\n- Sit upright for 30 min after (esophageal ulceration)\n- Photosensitivity — use sunscreen\n- Can be taken with food (unlike other tetracyclines)\n\n**Contraindications:**\n- Pregnancy, breastfeeding\n- Children <12 years (tooth discoloration)\n\n**Side effects:** Photosensitivity, nausea, esophageal irritation, vaginal candidiasis\n\n**Interactions:** Antacids, iron, calcium (reduce absorption — space 2h apart)', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'omeprazole', ARRAY['omeprazole','prilosec','ppi','proton pump inhibitor','acid reflux','gerd','ulcer','heartburn'], 'Omeprazole', E'## Omeprazole (Prilosec)\n\n**Class:** Proton Pump Inhibitor (PPI)\n**Indications:** GERD, peptic ulcer, H. pylori eradication, NSAID gastroprotection, Zollinger-Ellison\n\n**Dosing:**\n- GERD: 20mg once daily for 4-8 weeks\n- Peptic ulcer: 20-40mg daily for 4-8 weeks\n- H. pylori: 20mg BD (with 2 antibiotics) for 7-14 days\n- NSAID protection: 20mg daily\n\n**Key points:**\n- Take 30 min before breakfast\n- Short-term use preferred (<8 weeks)\n- Review need annually if long-term\n\n**Long-term risks:**\n- Magnesium deficiency\n- B12 deficiency\n- C. difficile infection\n- Osteoporotic fractures\n- Rebound acid hypersecretion on stopping\n\n**Side effects:** Headache, nausea, diarrhea, abdominal pain\n\n⚠️ **Taper rather than abrupt stop after long-term use**', 'en', 'BNF/NICE', 7, true),

('drug_reference', 'loperamide', ARRAY['loperamide','imodium','diarrhea','antidiarrheal','traveler diarrhea'], 'Loperamide', E'## Loperamide (Imodium)\n\n**Class:** Opioid antidiarrheal (peripheral acting)\n**Indication:** Acute non-specific diarrhea, traveler''s diarrhea\n\n**Dosing:**\n- Adult: 4mg initially, then 2mg after each loose stool (max 16mg/day)\n- Use for max 48 hours for acute diarrhea\n- Child >12: adult dose\n\n**Key points:**\n- Does NOT cross blood-brain barrier at therapeutic doses\n- Symptomatic relief only — does not treat cause\n- Ensure adequate oral rehydration\n\n**Contraindications:**\n- Dysentery (bloody diarrhea with fever)\n- Children <12 (without medical supervision)\n- Acute ulcerative colitis, C. difficile\n- Ileus, abdominal distension\n\n**Side effects:** Constipation, nausea, flatulence, abdominal cramps\n\n⚠️ **Do NOT use in invasive diarrhea (bloody/febrile) — may worsen infection**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'ors', ARRAY['ors','oral rehydration','dehydration','diarrhea','cholera','rehydration salts','electrolytes'], 'Oral Rehydration Solution (ORS)', E'## ORS (Oral Rehydration Solution)\n\n**Composition (WHO formula):**\n- Sodium chloride 2.6g, Glucose 13.5g\n- Potassium chloride 1.5g, Trisodium citrate 2.9g\n- Dissolved in 1L clean water\n\n**Dosing:**\n- Mild dehydration: 50-100mL/kg over 4 hours\n- Moderate: 100mL/kg over 4 hours\n- Maintenance: replace ongoing losses (10mL/kg per stool)\n- Children: small frequent sips or spoon-feeding\n\n**Key points:**\n- First-line treatment for dehydration from diarrhea\n- Continue breastfeeding during ORS\n- Zinc supplementation in children (20mg/day for 10-14 days)\n- Home-made: 6 teaspoons sugar + 1/2 teaspoon salt in 1L water\n\n**When to refer:**\n- Severe dehydration (IV fluids needed)\n- Persistent vomiting (cannot retain ORS)\n- Bloody diarrhea, high fever\n\n⚠️ **ORS saves lives — it is the single most important intervention for diarrheal disease**', 'en', 'WHO', 7, true),

('drug_reference', 'ferrous_sulfate', ARRAY['ferrous sulfate','iron','anemia','iron deficiency','hemoglobin','ferritin','iron supplement'], 'Ferrous Sulfate', E'## Ferrous Sulfate\n\n**Class:** Iron Supplement\n**Indication:** Iron deficiency anemia, prophylaxis in pregnancy\n\n**Dosing:**\n- Treatment: 200mg (65mg elemental iron) BD-TDS\n- Prophylaxis: 200mg once daily\n- Pregnancy: 200mg once daily (with folic acid)\n- Pediatric: 3-6mg/kg/day elemental iron\n\n**Key points:**\n- Take on empty stomach (better absorption)\n- Vitamin C (orange juice) enhances absorption\n- Takes 2-3 months to replenish stores\n- Continue 3 months after Hb normalizes\n- Check Hb at 2-4 weeks (should rise 1-2g/dL)\n\n**Side effects:**\n- Constipation, black stools (normal)\n- Nausea, abdominal pain\n- Diarrhea\n\n**Interactions:** Antacids, PPIs, tetracyclines, calcium (reduce absorption — space 2h)\n\n⚠️ **Iron overdose is dangerous in children — store safely**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'folic_acid', ARRAY['folic acid','folate','pregnancy','neural tube defect','anemia','supplementation','b9'], 'Folic Acid', E'## Folic Acid (Vitamin B9)\n\n**Indications:**\n- Neural tube defect prevention\n- Megaloblastic anemia\n- Methotrexate toxicity prevention\n\n**Dosing:**\n- Pre-conception + first 12 weeks: 400mcg daily\n- High risk (previous NTD, diabetes, epilepsy, BMI >30): 5mg daily\n- Megaloblastic anemia: 5mg daily for 4 months\n- With methotrexate: 5mg weekly (NOT on methotrexate day)\n\n**Key points:**\n- Start before conception ideally\n- Prevents 70% of neural tube defects\n- Safe in pregnancy at recommended doses\n- Check B12 before treating folate deficiency (masks B12 deficiency)\n\n**Side effects:** Generally well tolerated, rare GI upset\n\n⚠️ **Always check B12 before giving folate — may mask B12 deficiency and worsen neuropathy**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'vitamin_d', ARRAY['vitamin d','cholecalciferol','calciferol','bone health','rickets','osteoporosis','deficiency','sunshine vitamin'], 'Vitamin D', E'## Vitamin D (Cholecalciferol)\n\n**Indications:** Deficiency, rickets, osteoporosis prevention, hypoparathyroidism\n\n**Dosing:**\n- Maintenance: 800-1000 IU daily\n- Deficiency treatment: 50,000 IU weekly for 6-8 weeks, then maintenance\n- Children: 400-600 IU daily\n- High-risk groups: 800-2000 IU daily\n\n**Deficiency levels:**\n- Sufficient: >30 ng/mL (75 nmol/L)\n- Insufficient: 20-30 ng/mL\n- Deficient: <20 ng/mL\n- Severe: <10 ng/mL\n\n**High-risk groups:**\n- Limited sun exposure, dark skin\n- Elderly, institutionalized\n- Obese, malabsorption\n- Pregnancy, breastfeeding\n\n**Side effects (toxicity):** Hypercalcemia, nausea, confusion, renal stones (at very high doses)\n\n⚠️ **Check calcium and renal function before high-dose supplementation**', 'en', 'BNF/Endocrine Society', 7, true),

('drug_reference', 'calcium_supplement', ARRAY['calcium','calcium carbonate','calcium citrate','osteoporosis','bone','supplement','hypocalcemia'], 'Calcium Supplement', E'## Calcium Supplements\n\n**Types:**\n- Calcium carbonate: 40% elemental calcium (take with food)\n- Calcium citrate: 21% elemental (can take without food, better for elderly)\n\n**Dosing:**\n- Adult: 1000-1200mg elemental calcium daily (diet + supplement)\n- Osteoporosis: 1000mg daily with vitamin D\n- Pregnancy: 1000mg daily\n- Post-menopausal: 1200mg daily\n\n**Key points:**\n- Split doses (max 500mg per dose for absorption)\n- Take calcium carbonate with meals\n- Combine with vitamin D for bone health\n- Dietary sources preferred over supplements\n\n**Contraindications:**\n- Hypercalcemia, renal stones (calcium)\n- Sarcoidosis\n\n**Side effects:** Constipation, bloating, flatulence\n\n**Interactions:** Reduces absorption of iron, tetracyclines, levothyroxine (space 2-4 hours)\n\n⚠️ **Excess supplemental calcium may increase cardiovascular risk — dietary sources preferred**', 'en', 'BNF/WHO', 7, true),

('drug_reference', 'montelukast', ARRAY['montelukast','singulair','leukotriene','asthma','allergic rhinitis','exercise-induced asthma'], 'Montelukast', E'## Montelukast (Singulair)\n\n**Class:** Leukotriene Receptor Antagonist\n**Indications:** Asthma (add-on therapy), allergic rhinitis, exercise-induced bronchoconstriction\n\n**Dosing:**\n- Adult: 10mg once daily (evening)\n- Child 6-14y: 5mg chewable daily\n- Child 2-5y: 4mg chewable/granules daily\n\n**Key points:**\n- NOT a reliever — controller medication\n- Add-on to ICS if not controlled\n- Useful in aspirin-sensitive asthma\n- Also helps allergic rhinitis\n- Take in the evening\n\n**Contraindications:**\n- None absolute (well tolerated)\n\n**Side effects:**\n- Generally well tolerated\n- Headache, abdominal pain\n- **Neuropsychiatric:** agitation, sleep disturbances, depression, suicidal ideation (rare but FDA boxed warning)\n\n⚠️ **FDA boxed warning for neuropsychiatric events — discuss risk/benefit with patients**', 'en', 'BNF/FDA/GINA', 7, true),

('drug_reference', 'chlorpheniramine', ARRAY['chlorpheniramine','piriton','antihistamine','allergy','urticaria','hayfever','sedating','itching'], 'Chlorpheniramine', E'## Chlorpheniramine (Piriton)\n\n**Class:** First-generation antihistamine (sedating)\n**Indications:** Allergic rhinitis, urticaria, pruritus, anaphylaxis (adjunct)\n\n**Dosing:**\n- Adult: 4mg every 4-6 hours (max 24mg/day)\n- Child 6-12y: 2mg every 4-6 hours (max 12mg/day)\n- Child 1-5y: 1mg every 4-6 hours (max 6mg/day)\n- IM/IV (anaphylaxis): 10mg\n\n**Key points:**\n- Sedating — useful for itching at night\n- Part of anaphylaxis protocol (secondary)\n- Cheap and widely available\n\n**Contraindications:**\n- Neonates, premature infants\n- Concurrent MAOIs\n\n**Side effects:**\n- Drowsiness (main effect)\n- Dry mouth, urinary retention\n- Blurred vision, constipation\n- Paradoxical excitation in children\n\n⚠️ **May impair driving — advise patients**', 'en', 'BNF', 7, true),

('drug_reference', 'domperidone', ARRAY['domperidone','motilium','antiemetic','nausea','vomiting','gastroparesis','prokinetic'], 'Domperidone', E'## Domperidone (Motilium)\n\n**Class:** Dopamine antagonist (prokinetic/antiemetic)\n**Indications:** Nausea/vomiting, gastroparesis, functional dyspepsia\n\n**Dosing:**\n- Adult: 10mg TDS (before meals)\n- Max: 30mg/day\n- Duration: max 7 days\n- Child: 0.25mg/kg TDS\n\n**Key points:**\n- Does NOT cross blood-brain barrier well (fewer CNS effects than metoclopramide)\n- Preferred antiemetic in Parkinson''s disease\n- Also increases prolactin (can enhance lactation — off-label)\n\n**Contraindications:**\n- Cardiac conditions (QT prolongation)\n- Hepatic impairment (moderate-severe)\n- Concurrent QT-prolonging drugs\n- GI obstruction, perforation\n\n**Side effects:** Dry mouth, headache, QT prolongation, galactorrhea\n\n⚠️ **Risk of fatal cardiac arrhythmias — lowest dose, shortest duration**', 'en', 'BNF/EMA', 7, true),

('drug_reference', 'hyoscine', ARRAY['hyoscine','buscopan','scopolamine','antispasmodic','abdominal cramps','ibs','renal colic','motion sickness'], 'Hyoscine Butylbromide', E'## Hyoscine Butylbromide (Buscopan)\n\n**Class:** Anticholinergic/Antispasmodic\n**Indications:** Abdominal cramps, IBS, renal/biliary colic, dysmenorrhea\n\n**Dosing:**\n- Oral: 20mg QDS\n- IM/IV: 20mg, repeat after 30 min if needed (max 100mg/day)\n- IBS: 10mg TDS\n\n**Key points:**\n- Poorly absorbed orally (local GI effect)\n- Quick onset IV (5-10 min)\n- Does NOT cross blood-brain barrier well\n- Different from hyoscine hydrobromide (which does — used for motion sickness)\n\n**Contraindications:**\n- Paralytic ileus, mechanical obstruction\n- Myasthenia gravis\n- Prostatic hypertrophy with urinary retention\n- Tachycardia\n\n**Side effects:** Dry mouth, tachycardia, blurred vision, urinary retention, constipation\n\n⚠️ **IV route: risk of anaphylaxis — administer slowly with monitoring**', 'en', 'BNF', 7, true),

('clinical_guideline', 'diabetes_type2_management', ARRAY['diabetes','type 2','hba1c','metformin','glucose','management','lifestyle','insulin'], 'Type 2 Diabetes Management', E'## Type 2 Diabetes Management Guidelines\n\n**Targets:**\n- HbA1c: <7% (53 mmol/mol) general, <6.5% if newly diagnosed\n- Fasting glucose: 4-7 mmol/L\n- Post-meal: <10 mmol/L\n- BP: <130/80\n\n**Stepwise treatment:**\n1. **Step 1:** Lifestyle + Metformin 500mg → titrate to 2g/day\n2. **Step 2:** Add SU (gliclazide) OR DPP-4i OR SGLT2i\n3. **Step 3:** Triple therapy or add GLP-1 agonist\n4. **Step 4:** Basal insulin + oral agents\n\n**SGLT2i (empagliflozin, dapagliflozin):**\n- Cardiovascular and renal benefit\n- Prefer if heart failure or CKD\n\n**Annual screening:**\n- HbA1c, renal function, lipids\n- Eye screening, foot exam\n- Urine ACR (albumin-creatinine ratio)\n\n⚠️ **Sick day rules: stop metformin and SGLT2i during acute illness**', 'en', 'NICE/ADA', 6, true),

('clinical_guideline', 'hypertension_management', ARRAY['hypertension','blood pressure','high bp','antihypertensive','ace inhibitor','calcium channel blocker','management'], 'Hypertension Stepwise Treatment', E'## Hypertension Management Guidelines\n\n**Diagnosis:** ≥140/90 clinic BP, confirmed with ABPM (≥135/85)\n\n**Targets:**\n- <80 years: <140/90 (clinic) or <135/85 (ABPM)\n- ≥80 years: <150/90 (clinic)\n\n**NICE stepwise treatment:**\n1. **Step 1:**\n   - <55y or diabetic: ACEi (ramipril) or ARB (losartan)\n   - ≥55y or Black: CCB (amlodipine)\n2. **Step 2:** ACEi/ARB + CCB\n3. **Step 3:** ACEi/ARB + CCB + Thiazide-like diuretic (indapamide)\n4. **Step 4 (resistant):** Add spironolactone 25mg (if K+ ≤4.5)\n   - Or alpha-blocker/beta-blocker\n\n**Lifestyle:**\n- Salt <6g/day, alcohol moderation\n- Regular exercise, weight loss\n- DASH diet\n\n**Monitoring:** BP at each visit, renal function + electrolytes 1-2 weeks after starting ACEi/ARB\n\n⚠️ **ACEi/ARB contraindicated in pregnancy — switch to labetalol/nifedipine**', 'en', 'NICE/ESC', 6, true),

('clinical_guideline', 'asthma_action_plan', ARRAY['asthma','action plan','inhaler','step up','step down','peak flow','controller','reliever'], 'Asthma Action Plan', E'## Asthma Stepwise Management (BTS/SIGN)\n\n**Step 1:** SABA reliever PRN (salbutamol)\n**Step 2:** Add low-dose ICS (beclomethasone 200-400mcg/day)\n**Step 3:** Add LABA (salmeterol/formoterol) — NEVER LABA alone\n**Step 4:** Increase ICS to medium dose (800mcg/day) ± LTRA (montelukast)\n**Step 5:** High-dose ICS, oral prednisolone, specialist referral\n\n**Good control criteria:**\n- No daytime symptoms\n- No night-time waking\n- No exacerbations\n- No activity limitation\n- Normal lung function\n- SABA use ≤2 days/week\n\n**Peak flow zones:**\n- Green (>80%): continue normal treatment\n- Yellow (50-80%): step up, consider prednisolone\n- Red (<50%): emergency, seek medical help immediately\n\n**Review:** Every 3 months; step down if controlled for 3+ months\n\n⚠️ **Never prescribe LABA without ICS — increased mortality risk**', 'en', 'BTS/GINA', 6, true),

('clinical_guideline', 'copd_management', ARRAY['copd','chronic obstructive','emphysema','chronic bronchitis','spirometry','inhaler','exacerbation','smoking'], 'COPD Management', E'## COPD Management Guidelines\n\n**Diagnosis:** Spirometry: FEV1/FVC <0.7 post-bronchodilator\n\n**Severity (FEV1 % predicted):**\n- Mild: ≥80%, Moderate: 50-79%\n- Severe: 30-49%, Very severe: <30%\n\n**Stepwise treatment:**\n1. Smoking cessation (MOST IMPORTANT intervention)\n2. SABA/SAMA PRN\n3. LAMA (tiotropium) — first-line maintenance\n4. LAMA + LABA if persistent symptoms\n5. LAMA + LABA + ICS if frequent exacerbations (≥2/year)\n\n**Exacerbation management:**\n- Prednisolone 30mg for 5 days\n- Antibiotics if purulent sputum (amoxicillin or doxycycline)\n- Nebulized bronchodilators\n- Controlled oxygen (target SpO2 88-92%)\n\n**Annual care:**\n- Flu + pneumococcal vaccines\n- Pulmonary rehabilitation\n- BMI monitoring\n\n⚠️ **High-flow oxygen can cause CO2 retention in COPD — use controlled oxygen**', 'en', 'NICE/GOLD', 6, true),

('clinical_guideline', 'pregnancy_care', ARRAY['pregnancy','antenatal','prenatal','booking visit','folic acid','iron','ultrasound','gestational diabetes'], 'Pregnancy Care Guidelines', E'## Antenatal Care Guidelines\n\n**Pre-conception:**\n- Folic acid 400mcg daily (5mg if high risk)\n- Review medications for teratogenicity\n\n**Booking visit (8-12 weeks):**\n- Full history, BMI, BP\n- Blood group, Rh, antibodies\n- FBC, HIV, Hep B, syphilis, rubella\n- Urine culture\n- Dating ultrasound\n\n**Routine schedule:**\n- 11-14 weeks: NT scan + combined screening\n- 18-22 weeks: anatomy (anomaly) scan\n- 24-28 weeks: GTT if risk factors, anti-D if Rh-negative\n- 28 weeks: FBC, antibodies\n- 36 weeks: Check presentation\n- 41 weeks: Offer membrane sweep → induction at 41+3 to 42 weeks\n\n**Common supplements:**\n- Iron: if Hb <110 at booking, <105 at 28 weeks\n- Vitamin D: 400 IU daily throughout\n- Calcium: 1g daily if pre-eclampsia risk\n\n⚠️ **Avoid: ACEi, ARBs, statins, warfarin, retinoids, NSAIDs (3rd trimester)**', 'en', 'NICE/WHO', 6, true),

('clinical_guideline', 'anemia_workup', ARRAY['anemia','iron deficiency','hemoglobin','low hb','ferritin','blood test','b12','folate','workup'], 'Anemia Workup', E'## Anemia Workup Guidelines\n\n**Definition:** Hb <130 g/L (male), <120 g/L (female), <110 g/L (pregnancy)\n\n**Classification by MCV:**\n- **Microcytic (MCV <80):** Iron deficiency, thalassemia, chronic disease, sideroblastic\n- **Normocytic (80-100):** Chronic disease, renal, acute blood loss, bone marrow\n- **Macrocytic (>100):** B12/folate deficiency, alcohol, hypothyroid, myelodysplasia, liver disease\n\n**Iron deficiency workup:**\n1. Ferritin (best single test — low = diagnostic)\n2. Iron studies: low serum iron, high TIBC, low transferrin saturation\n3. If ferritin low → investigate cause:\n   - Menorrhagia, GI blood loss (refer for upper/lower GI investigation if male or post-menopausal)\n   - Dietary (vegetarian), malabsorption (celiac)\n\n**Treatment:**\n- Oral iron: ferrous sulfate 200mg BD-TDS for 3 months after Hb normalizes\n- IV iron if oral intolerant or rapid correction needed\n\n⚠️ **Unexplained iron deficiency in males/post-menopausal → exclude GI malignancy**', 'en', 'NICE/BSH', 6, true);
