
-- Seed medical knowledge base with comprehensive entries
-- RED FLAGS
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority) VALUES
('red_flags', 'chest_pain', ARRAY['chest','pain','cardiac','heart','pressure','tightness','angina','mi','myocardial'], 'Chest Pain - Cardiac Warning Signs', E'**URGENT REFERRAL** if: substernal pressure/tightness, radiating to left arm/jaw/back, diaphoresis, dyspnea, nausea. Duration >20min = call emergency immediately.\n- Troponin test required\n- ECG within 10 minutes\n- Aspirin 300mg chewable stat (if no contraindication)\n- Do NOT give Aspirin if: active bleeding, allergy, age <16\n- Emergency numbers: 1166/115 (PK), 997 (SA), 998 (AE)', 'en', 'AHA/WHO', 10),

('red_flags', 'stroke', ARRAY['stroke','face','arm','speech','time','weakness','numbness','slurred','fast','paralysis','drooping'], 'Stroke - FAST Assessment', E'**EMERGENCY** — Use FAST:\n- **F**ace: Ask to smile. Does one side droop?\n- **A**rms: Raise both arms. Does one drift down?\n- **S**peech: Repeat a phrase. Is it slurred/strange?\n- **T**ime: Call emergency IMMEDIATELY if any positive\n- Note exact time symptoms started (critical for treatment window)\n- tPA window: 4.5 hours from onset\n- Do NOT give food/water (aspiration risk)', 'en', 'AHA/WHO', 10),

('red_flags', 'pediatric_emergency', ARRAY['child','baby','infant','pediatric','fever','newborn','breathing','convulsion','seizure','dehydration','fontanelle'], 'Pediatric Emergency Signs', E'**URGENT** in children:\n- Fever >38°C in infant <3 months = ER immediately\n- Bulging fontanelle, persistent vomiting, lethargy\n- Breathing: nasal flaring, chest retractions, grunting\n- Seizure >5 minutes or first-time seizure\n- Signs of dehydration: no tears, dry mouth, sunken eyes, <3 wet diapers/day\n- Purple/non-blanching rash (meningococcal)\n- Refusal to feed in infants', 'en', 'WHO/IMCI', 10),

('red_flags', 'sepsis', ARRAY['sepsis','infection','fever','confusion','tachycardia','hypotension','rapid','breathing','sofa','qsofa'], 'Sepsis Warning Signs (qSOFA)', E'**URGENT** — Suspect sepsis if infection + any 2 of:\n- Respiratory rate ≥22/min\n- Altered mental status/confusion\n- Systolic BP ≤100 mmHg\nAdditional signs: Temperature >38.3°C or <36°C, Heart rate >90, Lactate >2\n→ Requires IMMEDIATE hospital referral and IV antibiotics within 1 hour', 'en', 'Surviving Sepsis', 10),

('red_flags', 'anaphylaxis', ARRAY['allergy','allergic','anaphylaxis','swelling','throat','breathing','hives','epinephrine','epipen','rash','wheezing'], 'Anaphylaxis Emergency', E'**LIFE-THREATENING** — Signs:\n- Throat/tongue swelling, difficulty breathing/swallowing\n- Widespread hives/urticaria + any respiratory/cardiovascular symptom\n- Rapid onset after allergen exposure\n**IMMEDIATE ACTION**:\n- Epinephrine (adrenaline) 0.3-0.5mg IM mid-outer thigh (EpiPen if available)\n- Call emergency services\n- Lay flat, elevate legs (unless breathing difficulty)\n- Second dose after 5-15 min if no improvement\n- Antihistamines are NOT sufficient alone', 'en', 'WAO/EAACI', 10),

('red_flags', 'appendicitis', ARRAY['appendix','appendicitis','right','lower','abdomen','rebound','tenderness','mcburney','nausea','fever'], 'Appendicitis Warning Signs', E'**SURGICAL EMERGENCY** if suspected:\n- Pain starting around navel, migrating to right lower quadrant (McBurney point)\n- Rebound tenderness, guarding\n- Low-grade fever, nausea/vomiting, loss of appetite\n- Pain worsens with movement, coughing, walking\n→ Do NOT give painkillers before surgical evaluation\n→ Do NOT eat or drink (NPO for possible surgery)\n→ Refer to ER for ultrasound/CT and surgical consult', 'en', 'Clinical', 9),

('red_flags', 'meningitis', ARRAY['meningitis','neck','stiffness','headache','fever','rash','photophobia','kernig','brudzinski','confusion'], 'Meningitis Warning Signs', E'**EMERGENCY** if fever + headache + any of:\n- Neck stiffness (cannot touch chin to chest)\n- Photophobia (light sensitivity)\n- Non-blanching petechial/purpuric rash\n- Altered consciousness, confusion\n- Kernig/Brudzinski signs positive\n→ Requires IMMEDIATE hospital admission\n→ IV antibiotics within 1 hour of suspicion\n→ In children: irritability, bulging fontanelle, high-pitched cry', 'en', 'WHO/NICE', 10),

('red_flags', 'dvt_pe', ARRAY['dvt','clot','leg','swelling','calf','pulmonary','embolism','breathless','chest','pain','hemoptysis'], 'DVT/Pulmonary Embolism', E'**DVT signs**: Unilateral leg swelling, warmth, redness, calf pain (Homan sign)\nRisk factors: recent surgery, immobilization, long travel, OCP use, pregnancy\n**PE signs**: Sudden breathlessness, pleuritic chest pain, hemoptysis, tachycardia\n→ Urgent referral for D-dimer + Doppler US (DVT) or CT-PA (PE)\n→ Do NOT massage affected leg\n→ Anticoagulation needed within hours', 'en', 'NICE/ESC', 9),

('red_flags', 'diabetic_emergency', ARRAY['diabetes','sugar','glucose','dka','ketoacidosis','hypoglycemia','unconscious','fruity','breath','thirst'], 'Diabetic Emergency Signs', E'**DKA (Diabetic Ketoacidosis)**:\n- Blood glucose >250mg/dL + nausea/vomiting + abdominal pain\n- Fruity breath odor, Kussmaul breathing (deep/rapid)\n- Dehydration, confusion → ER immediately\n**Hypoglycemia** (<70mg/dL):\n- Trembling, sweating, confusion, irritability\n- If conscious: 15g fast-acting sugar (3-4 glucose tablets, half cup juice)\n- Recheck in 15 min, repeat if still low\n- If unconscious: DO NOT give oral food → call emergency', 'en', 'ADA', 9),

('red_flags', 'ectopic_pregnancy', ARRAY['ectopic','pregnancy','bleeding','vaginal','pain','missed','period','shoulder','tip','positive','test'], 'Ectopic Pregnancy Warning', E'**LIFE-THREATENING** — Suspect if:\n- Positive pregnancy test + lower abdominal/pelvic pain (usually one-sided)\n- Vaginal bleeding (often dark/scanty)\n- Shoulder tip pain (sign of internal bleeding/diaphragm irritation)\n- Dizziness, fainting, tachycardia (signs of rupture)\n→ IMMEDIATE ER referral\n→ Urgent transvaginal ultrasound + beta-hCG\n→ Ruptured ectopic = surgical emergency', 'en', 'RCOG', 10);

-- DRUG REFERENCES
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority) VALUES
('drug_reference', 'pain_fever', ARRAY['paracetamol','acetaminophen','panadol','fever','pain','headache','tylenol','temperature'], 'Paracetamol (Acetaminophen)', E'**Paracetamol / Panadol / Tylenol**\n- Adult: 500mg-1g every 4-6 hours, MAX 4g/day\n- Child 6-12yr: 250-500mg every 4-6 hours\n- Child 1-5yr: 120-250mg every 4-6 hours (use syrup: 120mg/5ml)\n- Infant 3-12mo: 60-120mg every 4-6 hours\n⚠️ Contraindicated: severe liver disease, alcohol dependence\n⚠️ Hepatotoxic in overdose (>150mg/kg)\nSafe in pregnancy. First-line for fever and mild-moderate pain.', 'en', 'BNF', 8),

('drug_reference', 'pain_inflammation', ARRAY['ibuprofen','brufen','nsaid','pain','inflammation','swelling','arthritis','muscle','joint','advil'], 'Ibuprofen (Brufen)', E'**Ibuprofen / Brufen / Advil**\n- Adult: 200-400mg every 6-8 hours, MAX 1.2g/day (OTC)\n- Child >3mo: 5-10mg/kg every 6-8 hours\n⚠️ Take WITH food to protect stomach\n⚠️ Contraindicated: peptic ulcer, renal impairment, 3rd trimester pregnancy, aspirin allergy\n⚠️ Avoid in: asthma (may worsen), heart failure, elderly with GI risk\nDo NOT combine with other NSAIDs. Can alternate with Paracetamol.', 'en', 'BNF', 8),

('drug_reference', 'acid_reflux', ARRAY['omeprazole','prilosec','acid','reflux','gerd','heartburn','stomach','gastric','ppi','ulcer','acidity'], 'Omeprazole (PPI)', E'**Omeprazole / Prilosec**\n- Adult: 20mg once daily before breakfast (can increase to 40mg)\n- Duration: 2-4 weeks for GERD, 4-8 weeks for ulcer\n⚠️ Take 30min BEFORE first meal of the day\n⚠️ Long-term use risks: vitamin B12/magnesium deficiency, bone fractures\n⚠️ Drug interactions: clopidogrel (avoid combo), methotrexate\nAlternatives: Esomeprazole 20mg, Lansoprazole 15-30mg', 'en', 'BNF', 7),

('drug_reference', 'allergy', ARRAY['cetirizine','zyrtec','allergy','antihistamine','hives','urticaria','rhinitis','itching','sneezing','runny','nose'], 'Cetirizine (Zyrtec)', E'**Cetirizine / Zyrtec**\n- Adult & child >12yr: 10mg once daily\n- Child 6-12yr: 5mg twice daily or 10mg once daily\n- Child 2-6yr: 2.5mg twice daily or 5mg once daily\n⚠️ May cause drowsiness (less than older antihistamines)\n⚠️ Reduce dose in renal impairment\nAlternatives: Loratadine 10mg (less sedating), Fexofenadine 120-180mg', 'en', 'BNF', 7),

('drug_reference', 'cough', ARRAY['cough','dextromethorphan','guaifenesin','expectorant','suppressant','mucus','phlegm','dry','productive'], 'Cough Medications', E'**Dry Cough (non-productive)**:\n- Dextromethorphan 10-20mg every 4-6 hours (adult)\n- Honey + warm water (evidence-based, safe >1yr)\n⚠️ Do NOT suppress productive cough\n**Wet/Productive Cough**:\n- Guaifenesin 200-400mg every 4 hours\n- Increase fluid intake\n- Steam inhalation\n⚠️ Cough >3 weeks = needs investigation\n⚠️ Avoid codeine in children <12yr\n⚠️ No honey for infants <1yr (botulism risk)', 'en', 'BNF', 7),

('drug_reference', 'diarrhea', ARRAY['diarrhea','diarrhoea','ors','loperamide','imodium','dehydration','loose','stool','gastroenteritis','vomiting'], 'Diarrhea Management', E'**First-line: ORS (Oral Rehydration Solution)**\n- Adult: sip frequently, 200ml after each loose stool\n- Child: 50-100ml after each stool (age-dependent)\n**Loperamide (Imodium)** — adults only:\n- Initial: 4mg, then 2mg after each loose stool, MAX 16mg/day\n⚠️ Do NOT use loperamide if: bloody diarrhea, fever >38.5°C, children <12yr\n⚠️ Do NOT use in suspected bacterial dysentery\nZinc supplement 20mg/day for 10-14 days in children (WHO recommendation)', 'en', 'WHO/BNF', 8),

('drug_reference', 'pain_strong', ARRAY['diclofenac','voltaren','ponstan','mefenamic','pain','strong','muscle','back','toothache','menstrual','cramps'], 'Diclofenac & Mefenamic Acid', E'**Diclofenac (Voltaren)**:\n- Adult: 50mg 2-3 times daily WITH food, MAX 150mg/day\n- Topical gel: apply 3-4 times daily to affected area\n⚠️ Same contraindications as ibuprofen (NSAID)\n**Mefenamic Acid (Ponstan)**:\n- Adult: 500mg 3 times daily WITH food\n- Best for: menstrual cramps, dental pain\n- MAX duration: 7 days\n⚠️ More GI side effects than ibuprofen\n⚠️ Both contraindicated in renal impairment, GI bleeding, pregnancy 3rd trimester', 'en', 'BNF', 7),

('drug_reference', 'antibiotics_common', ARRAY['antibiotic','amoxicillin','azithromycin','augmentin','infection','bacteria','prescription'], 'Common Antibiotics (Rx Only)', E'**⚠️ PRESCRIPTION REQUIRED — Do not self-medicate**\n**Amoxicillin**: 500mg 3x/day for 5-7 days (UTI, respiratory, dental)\n**Augmentin** (Amoxicillin+Clavulanate): 625mg 2x/day (resistant infections)\n**Azithromycin**: 500mg day 1, then 250mg days 2-5 (respiratory, STI)\n**Ciprofloxacin**: 500mg 2x/day (UTI, GI infections)\n⚠️ Always complete full course\n⚠️ Ciprofloxacin: avoid in children, tendon rupture risk\n⚠️ Tell patient: "Your doctor may prescribe [X] — this requires a prescription."', 'en', 'BNF/WHO', 7),

('drug_reference', 'antacid', ARRAY['antacid','gaviscon','tums','calcium','carbonate','aluminium','magnesium','indigestion','bloating'], 'Antacids (Quick Relief)', E'**Antacids — For quick symptom relief:**\n- Calcium carbonate (Tums): 500-1000mg as needed, chew before swallowing\n- Aluminium/Magnesium hydroxide (Maalox): 10-20ml after meals & bedtime\n- Gaviscon: 10-20ml after meals (forms raft over stomach acid)\n⚠️ Antacids interact with many drugs — take 2 hours apart from other medications\n⚠️ If symptoms persist >2 weeks: switch to PPI (Omeprazole)\n⚠️ Magnesium-based: may cause diarrhea\n⚠️ Aluminium-based: may cause constipation', 'en', 'BNF', 6),

('drug_reference', 'eye_drops', ARRAY['eye','drops','conjunctivitis','red','itchy','dry','tear','infection','pink','eye'], 'Eye Medications', E'**Dry Eyes**: Artificial tears (Systane, Refresh) — use as needed\n**Allergic conjunctivitis**: Olopatadine 0.1% or Ketotifen drops 2x/day\n**Bacterial conjunctivitis** (yellow/green discharge):\n- Chloramphenicol drops: 1 drop every 2 hours for 48hr, then 4x/day for 5 days\n- OR Fusidic acid gel: 1 drop 2x/day for 7 days\n⚠️ If vision affected, severe pain, or photophobia → urgent ophthalmology referral\n⚠️ Contact lens wearers: remove lenses during treatment', 'en', 'BNF', 6);

-- CLINICAL GUIDELINES
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority) VALUES
('clinical_guideline', 'uti', ARRAY['uti','urinary','tract','infection','burning','urination','frequency','dysuria','bladder','cystitis','urine'], 'UTI Management Guideline', E'**Uncomplicated UTI (Cystitis) in Women:**\n- Symptoms: dysuria, frequency, urgency, suprapubic pain\n- First-line: Nitrofurantoin 100mg 2x/day for 5 days (Rx)\n- Alternative: Trimethoprim 200mg 2x/day for 3 days (Rx)\n- Supportive: increase fluid intake, cranberry (limited evidence)\n**Red flags (→ complicated UTI/pyelonephritis):**\n- Fever, flank pain, rigors, nausea/vomiting\n- Male UTI = always investigate\n- Recurrent UTI (≥3/year) = needs urology referral\n⚠️ In pregnancy: MUST treat + follow up culture', 'en', 'NICE/WHO', 7),

('clinical_guideline', 'hypertension', ARRAY['hypertension','blood','pressure','high','bp','systolic','diastolic','cardiovascular'], 'Hypertension Guidelines', E'**Classification:**\n- Normal: <120/80\n- Elevated: 120-129/<80\n- Stage 1: 130-139/80-89\n- Stage 2: ≥140/≥90\n- Crisis: >180/>120 → ER immediately\n**Lifestyle modifications (ALL stages):**\n- DASH diet, reduce sodium <2g/day, exercise 150min/week\n- Limit alcohol, quit smoking, manage stress\n**When to start medication:** Stage 1 with risk factors, or Stage 2\n⚠️ Target: <130/80 for most adults\n⚠️ Check for secondary causes if: age <30, resistant hypertension', 'en', 'ACC/AHA', 7),

('clinical_guideline', 'diabetes_type2', ARRAY['diabetes','type2','sugar','glucose','hba1c','metformin','insulin','fasting','blood','sugar'], 'Type 2 Diabetes Management', E'**Diagnosis:**\n- Fasting glucose ≥126mg/dL (7.0 mmol/L)\n- HbA1c ≥6.5%\n- Random glucose ≥200mg/dL with symptoms\n**First-line: Metformin** 500mg with dinner, titrate to 1000mg 2x/day\n**Targets:** HbA1c <7%, FBS 80-130mg/dL, post-meal <180mg/dL\n**Monitoring:** HbA1c every 3 months, annual eye/foot/kidney check\n⚠️ Metformin: hold if eGFR <30, before contrast dye\n⚠️ Hypoglycemia signs: tremor, sweating, confusion → 15g sugar rule', 'en', 'ADA', 7),

('clinical_guideline', 'gerd', ARRAY['gerd','reflux','heartburn','acid','chest','burning','regurgitation','esophagus','gastroesophageal'], 'GERD Management', E'**Lifestyle (First-line):**\n- Elevate head of bed 6-8 inches\n- Avoid: spicy food, caffeine, chocolate, fatty food, late meals\n- No eating 2-3 hours before bed\n- Weight loss if overweight\n**Medication step-up:**\n1. Antacids PRN (mild, <2x/week)\n2. H2 blocker: Famotidine 20mg 2x/day (moderate)\n3. PPI: Omeprazole 20mg daily for 4-8 weeks (frequent)\n⚠️ Alarm features (→ endoscopy): dysphagia, weight loss, anemia, GI bleeding, age >55 new onset', 'en', 'ACG', 7),

('clinical_guideline', 'migraine', ARRAY['migraine','headache','aura','throbbing','nausea','photophobia','unilateral','visual','trigger'], 'Migraine Management', E'**Acute Treatment:**\n- Mild: Paracetamol 1g + Caffeine, or Ibuprofen 400mg\n- Moderate-Severe: Sumatriptan 50-100mg (Rx) at onset, can repeat after 2hr\n- Anti-emetic: Metoclopramide 10mg or Domperidone 10mg\n⚠️ Triptans contraindicated in: ischemic heart disease, uncontrolled HTN, basilar migraine\n**Prevention (if ≥4 attacks/month):** Propranolol 40-80mg 2x/day, or Amitriptyline 10-25mg at night (Rx)\n**Red flags (→ imaging):** thunderclap onset, worst headache ever, focal neurological signs, age >50 new onset, fever + headache', 'en', 'NICE/IHS', 7),

('clinical_guideline', 'asthma', ARRAY['asthma','wheezing','breathless','inhaler','salbutamol','ventolin','steroid','bronchospasm','cough','night'], 'Asthma Management', E'**Acute attack at home:**\n- Salbutamol (Ventolin) inhaler: 4-6 puffs via spacer, repeat every 20 min x3\n- If no improvement after 3 rounds → ER immediately\n- Prednisolone 40-50mg for 5 days if moderate-severe (Rx)\n**Step-wise maintenance:**\n1. SABA PRN (Salbutamol)\n2. Low-dose ICS (Beclomethasone 200mcg/day)\n3. Add LABA (Formoterol) or increase ICS\n⚠️ Red flags: unable to complete sentences, silent chest, cyanosis, drowsiness → EMERGENCY\n⚠️ Using reliever >2x/week = uncontrolled → step up', 'en', 'GINA', 7);

-- SYMPTOM GUIDES
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority) VALUES
('symptom_guide', 'abdominal_pain', ARRAY['stomach','abdomen','abdominal','pain','belly','cramp','bloating','gas','nausea'], 'Abdominal Pain Differential', E'**Location-based differentials:**\n- **Right upper**: gallstones, hepatitis, pneumonia (referred)\n- **Epigastric**: GERD, peptic ulcer, pancreatitis, MI (referred)\n- **Left upper**: splenic pathology, gastritis\n- **Right lower**: appendicitis, ovarian cyst, ectopic pregnancy\n- **Left lower**: diverticulitis, IBS, constipation\n- **Suprapubic**: UTI, bladder, gynecological\n- **Diffuse**: gastroenteritis, IBS, obstruction\n**Key questions:** onset, location, radiation, character, timing, aggravating/relieving factors, associated symptoms', 'en', 'Clinical', 6),

('symptom_guide', 'headache', ARRAY['headache','head','pain','tension','migraine','cluster','sinus','temporal','frontal','occipital'], 'Headache Differential', E'**Common types:**\n- **Tension**: bilateral, band-like, mild-moderate, no nausea\n- **Migraine**: unilateral, throbbing, moderate-severe, nausea, photophobia, +/- aura\n- **Cluster**: unilateral, orbital/temporal, severe, lacrimation, rhinorrhea, occurs in clusters\n- **Sinus**: frontal/maxillary, worse bending forward, nasal congestion\n- **Medication overuse**: daily headache from frequent analgesic use (>15 days/month)\n**Red flags (→ urgent):** thunderclap, worst ever, focal neuro signs, papilledema, fever + neck stiffness, post-trauma, age >50 new onset', 'en', 'Clinical', 6),

('symptom_guide', 'fever', ARRAY['fever','temperature','hot','chills','rigor','sweating','infection','pyrexia','flu','cold'], 'Fever Assessment Guide', E'**Definition:** Temperature >38°C (100.4°F)\n**Common causes:** Viral URI (most common), UTI, pneumonia, gastroenteritis, dengue (in endemic areas)\n**Assessment questions:**\n- Duration? (>5 days needs investigation)\n- Associated symptoms? (cough, dysuria, rash, joint pain)\n- Recent travel? (malaria, typhoid, dengue)\n- Sick contacts?\n**Management:**\n- Paracetamol 500-1000mg every 6hr for comfort\n- Adequate fluids\n- Light clothing, tepid sponging\n⚠️ Urgent if: rash, neck stiffness, confusion, seizures, infant <3mo', 'en', 'Clinical', 6),

('symptom_guide', 'sore_throat', ARRAY['throat','sore','pain','swallowing','tonsil','pharyngitis','strep','hoarse','voice'], 'Sore Throat Assessment', E'**Most cases are VIRAL** (70-80%) — antibiotics NOT needed\n**Centor criteria (bacterial likelihood):**\n- Tonsillar exudate (+1)\n- Tender anterior cervical lymph nodes (+1)\n- Fever >38°C (+1)\n- Absence of cough (+1)\nScore ≥3: consider antibiotics (Penicillin V 500mg 2x/day for 10 days)\nScore <3: symptomatic treatment only\n**Symptomatic relief:**\n- Warm salt water gargle\n- Paracetamol/Ibuprofen for pain\n- Lozenges (Strepsils, etc.)\n⚠️ Urgent if: drooling, trismus, unilateral swelling (peritonsillar abscess), stridor', 'en', 'NICE/Centor', 6),

('symptom_guide', 'back_pain', ARRAY['back','pain','lumbar','spine','sciatica','disc','herniation','muscle','strain','lower'], 'Back Pain Assessment', E'**Most back pain is mechanical** (>90%) — resolves in 4-6 weeks\n**Red flags (→ urgent imaging/referral):**\n- Cauda equina: saddle anesthesia, urinary retention, bilateral leg weakness → EMERGENCY\n- Age >50 or <20 with new back pain\n- Weight loss, fever, night sweats (infection/cancer)\n- History of cancer\n- Progressive neurological deficit\n**Management of mechanical back pain:**\n- Stay active (bed rest worsens outcome)\n- Paracetamol + NSAIDs (Ibuprofen 400mg 3x/day)\n- Heat application\n- Return to normal activities ASAP\n⚠️ Sciatica: leg pain > back pain, follows dermatome', 'en', 'NICE', 6),

('symptom_guide', 'skin_rash', ARRAY['rash','skin','itchy','red','bumps','hives','eczema','dermatitis','fungal','allergy','spots'], 'Skin Rash Assessment', E'**Common presentations:**\n- **Urticaria/Hives**: raised, itchy wheals, comes and goes → antihistamine (Cetirizine 10mg)\n- **Eczema**: dry, itchy, flexural areas → emollients + mild steroid (Hydrocortisone 1%)\n- **Contact dermatitis**: localized to exposure area → remove trigger + steroid cream\n- **Fungal (tinea)**: circular, scaly border, central clearing → Clotrimazole cream 2x/day for 2-4 weeks\n- **Scabies**: intense itch (worse at night), web spaces, wrists → Permethrin 5% cream\n⚠️ Urgent: non-blanching purpura (glass test), widespread blistering, mucous membrane involvement, systemic symptoms', 'en', 'Clinical', 6),

('symptom_guide', 'dizziness', ARRAY['dizzy','dizziness','vertigo','lightheaded','spinning','balance','faint','room','spinning','unsteady'], 'Dizziness Differential', E'**Types:**\n- **Vertigo** (room spinning): BPPV (most common), labyrinthitis, Ménière disease\n- **Presyncope** (feeling faint): dehydration, orthostatic hypotension, cardiac\n- **Disequilibrium** (unsteady): medication effect, neuropathy\n**BPPV**: brief episodes triggered by head position, Epley maneuver is treatment\n**Labyrinthitis**: vertigo + hearing loss, often post-viral\n**Management**: Meclizine 25mg 3x/day or Betahistine 16mg 3x/day for vertigo\n⚠️ Urgent: vertigo + focal neuro signs (stroke), sudden hearing loss, persistent vomiting', 'en', 'Clinical', 6);

-- Arabic key entries
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority) VALUES
('red_flags', 'chest_pain', ARRAY['صدر','ألم','قلب','ضغط','ضيق','ذبحة'], 'ألم الصدر - علامات خطر قلبية', E'**إحالة عاجلة** إذا: ضغط/ضيق خلف القص، ينتشر للذراع الأيسر/الفك/الظهر، تعرق، ضيق تنفس، غثيان\n- مدة >20 دقيقة = اتصل بالطوارئ فوراً\n- أسبرين 300 ملغ مضغ (إذا لا مانع)\n- لا تعطِ أسبرين إذا: نزيف، حساسية، عمر <16', 'ar', 'AHA/WHO', 10),

('drug_reference', 'pain_fever', ARRAY['باراسيتامول','حرارة','ألم','صداع','بنادول','حمى'], 'باراسيتامول (بنادول)', E'**باراسيتامول / بنادول**\n- بالغ: 500 ملغ-1 غرام كل 4-6 ساعات، أقصى حد 4 غرام يومياً\n- طفل 6-12 سنة: 250-500 ملغ كل 4-6 ساعات\n- طفل 1-5 سنوات: 120-250 ملغ كل 4-6 ساعات\n⚠️ ممنوع: أمراض الكبد الشديدة\nآمن في الحمل. الخيار الأول للحرارة والألم الخفيف-المتوسط.', 'ar', 'BNF', 8);

-- Urdu key entries
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority) VALUES
('red_flags', 'chest_pain', ARRAY['سینے','درد','دل','دباؤ','تنگی','انجائنا'], 'سینے کا درد - دل کی خطرناک علامات', E'**فوری حوالہ** اگر: سینے کے پیچھے دباؤ/تنگی، بائیں بازو/جبڑے/کمر تک پھیلنا، پسینہ، سانس کی تنگی\n- 20 منٹ سے زیادہ = فوری ایمرجنسی\n- ایسپرین 300mg چبا کر (اگر کوئی ممانعت نہ ہو)\n- ایمرجنسی: 1166 (ریسکیو)، 115 (ایدھی)', 'ur', 'AHA/WHO', 10),

('drug_reference', 'pain_fever', ARRAY['پیراسیٹامول','بخار','درد','سر','درد','پینا','ڈول'], 'پیراسیٹامول (پینا ڈول)', E'**پیراسیٹامول / پینا ڈول**\n- بالغ: 500mg-1g ہر 4-6 گھنٹے، زیادہ سے زیادہ 4g روزانہ\n- بچے 6-12 سال: 250-500mg ہر 4-6 گھنٹے\n- بچے 1-5 سال: 120-250mg ہر 4-6 گھنٹے (شربت استعمال کریں)\n⚠️ جگر کی شدید بیماری میں ممنوع\nحمل میں محفوظ۔ بخار اور ہلکے درد کے لیے پہلی پسند۔', 'ur', 'BNF', 8);
