
INSERT INTO public.medical_knowledge (category, condition, keywords, title, content, language, source, priority, is_active) VALUES
('red_flags', 'dvt_pe', ARRAY['dvt','deep vein thrombosis','pe','pulmonary embolism','leg swelling','calf pain','breathlessness','blood clot'], 'Deep Vein Thrombosis / Pulmonary Embolism', E'## DVT/PE Red Flags\n\n**Suspect DVT if:**\n- Unilateral leg swelling, warmth, redness\n- Calf pain on dorsiflexion (Homan''s sign)\n- Recent surgery, immobilization, or long travel\n\n**Suspect PE if:**\n- Sudden dyspnea, pleuritic chest pain\n- Tachycardia, hemoptysis\n- History of DVT or risk factors\n\n**Immediate action:**\n- Wells score assessment\n- D-dimer if low probability\n- CT pulmonary angiography if high probability\n- Start anticoagulation (LMWH) if high clinical suspicion\n\n⚠️ **EMERGENCY: Massive PE with hemodynamic instability → thrombolysis or embolectomy**', 'en', 'NICE/BTS', 10, true),

('red_flags', 'dka', ARRAY['dka','diabetic ketoacidosis','high sugar','ketones','fruity breath','kussmaul','dehydration','diabetes emergency'], 'Diabetic Ketoacidosis (DKA)', E'## DKA Red Flags\n\n**Classic triad:**\n- Hyperglycemia (>11 mmol/L / 200 mg/dL)\n- Metabolic acidosis (pH <7.3, bicarb <15)\n- Ketonemia/ketonuria\n\n**Warning signs:**\n- Nausea, vomiting, abdominal pain\n- Kussmaul breathing (deep, rapid)\n- Fruity breath odor\n- Confusion, drowsiness\n- Dehydration\n\n**Immediate action:**\n- IV normal saline bolus\n- IV insulin infusion (0.1 units/kg/hr)\n- Potassium replacement (check K+ before insulin)\n- Monitor glucose hourly, electrolytes 2-hourly\n\n⚠️ **EMERGENCY: Cerebral edema risk in children — avoid rapid glucose correction**', 'en', 'ADA/WHO', 10, true),

('red_flags', 'ectopic_pregnancy', ARRAY['ectopic','pregnancy','vaginal bleeding','abdominal pain','missed period','positive pregnancy test','shoulder tip pain'], 'Ectopic Pregnancy', E'## Ectopic Pregnancy Red Flags\n\n**Suspect if:**\n- Positive pregnancy test + abdominal/pelvic pain\n- Vaginal bleeding in early pregnancy (6-8 weeks)\n- Shoulder tip pain (diaphragmatic irritation)\n- Syncope or dizziness\n\n**Risk factors:**\n- Previous ectopic, PID, tubal surgery\n- IUD in situ, assisted conception\n\n**Immediate action:**\n- Urgent transvaginal ultrasound\n- Serial β-hCG if inconclusive\n- IV access, crossmatch blood\n- Surgical referral if ruptured\n\n⚠️ **EMERGENCY: Ruptured ectopic → hemorrhagic shock → immediate laparotomy**', 'en', 'RCOG/WHO', 10, true),

('red_flags', 'acute_abdomen', ARRAY['acute abdomen','peritonitis','rigid abdomen','guarding','rebound tenderness','surgical abdomen','appendicitis','perforation'], 'Acute Abdomen', E'## Acute Abdomen Red Flags\n\n**Signs of surgical emergency:**\n- Board-like rigidity\n- Rebound tenderness\n- Absent bowel sounds\n- Involuntary guarding\n\n**Common causes:**\n- Appendicitis, perforated ulcer\n- Bowel obstruction, volvulus\n- Ruptured AAA, mesenteric ischemia\n\n**Immediate action:**\n- NPO (nil per os)\n- IV fluids, analgesia\n- Urgent bloods (FBC, amylase, lactate)\n- Erect CXR (free air under diaphragm)\n- Urgent surgical review\n\n⚠️ **Do NOT delay surgical referral for imaging if patient is hemodynamically unstable**', 'en', 'WHO/Surgical', 10, true),

('red_flags', 'meningitis', ARRAY['meningitis','neck stiffness','photophobia','rash','non-blanching','fever','headache','kernig','brudzinski'], 'Meningitis', E'## Meningitis Red Flags\n\n**Classic triad:**\n- Fever, headache, neck stiffness\n\n**Additional signs:**\n- Photophobia, phonophobia\n- Non-blanching petechial rash (meningococcal)\n- Altered consciousness\n- Kernig/Brudzinski signs positive\n- Bulging fontanelle (infants)\n\n**Immediate action:**\n- Do NOT wait for LP — give empirical antibiotics\n- IV/IM Ceftriaxone 2g (adult) or 50mg/kg (child)\n- Dexamethasone before or with first antibiotic dose\n- Blood cultures before antibiotics if possible\n\n⚠️ **EMERGENCY: Meningococcal septicemia — time to antibiotics is critical**', 'en', 'NICE/WHO', 10, true),

('red_flags', 'suicidal_ideation', ARRAY['suicide','suicidal','self-harm','overdose','want to die','hopeless','depression','mental health emergency'], 'Suicidal Ideation', E'## Suicidal Ideation Red Flags\n\n**Assess immediately if patient expresses:**\n- Thoughts of ending their life\n- Feeling like a burden to others\n- Hopelessness, no reason to live\n- History of previous attempts\n\n**Risk assessment (SAD PERSONS):**\n- Sex (male higher risk), Age (<19 or >45)\n- Depression, Previous attempt\n- Ethanol/drug abuse\n- Rational thinking loss\n- Social support lacking\n- Organized plan, No spouse\n- Sickness (chronic illness)\n\n**Immediate action:**\n- Do not leave patient alone\n- Remove access to means\n- Urgent psychiatric referral\n- Safety plan if outpatient\n\n⚠️ **EMERGENCY: Active plan with means → immediate psychiatric admission**', 'en', 'WHO/mhGAP', 10, true),

('red_flags', 'hypertensive_crisis', ARRAY['hypertensive crisis','hypertensive emergency','blood pressure','high bp','severe hypertension','headache','vision changes','encephalopathy'], 'Hypertensive Crisis', E'## Hypertensive Crisis Red Flags\n\n**Hypertensive emergency (BP >180/120 + organ damage):**\n- Severe headache, visual disturbance\n- Chest pain (aortic dissection, MI)\n- Dyspnea (pulmonary edema)\n- Neurological deficit (stroke)\n- Encephalopathy (confusion, seizures)\n\n**Hypertensive urgency (BP >180/120, no organ damage):**\n- Gradually reduce BP over 24-48 hours\n- Oral medications sufficient\n\n**Immediate action for emergency:**\n- IV labetalol or nicardipine\n- Target: reduce MAP by 25% in first hour\n- Do NOT drop BP too rapidly\n- ECG, renal function, CT head if neuro symptoms\n\n⚠️ **Rapid BP reduction can cause watershed infarcts**', 'en', 'AHA/ESC', 10, true),

('red_flags', 'hypoglycemia', ARRAY['hypoglycemia','low sugar','low blood sugar','shaking','sweating','confusion','unconscious','diabetes','insulin'], 'Hypoglycemia', E'## Hypoglycemia Red Flags\n\n**Blood glucose <4 mmol/L (70 mg/dL)**\n\n**Adrenergic symptoms:**\n- Tremor, sweating, palpitations\n- Anxiety, hunger, pallor\n\n**Neuroglycopenic symptoms:**\n- Confusion, drowsiness\n- Seizures, loss of consciousness\n- Behavioral changes\n\n**Immediate action:**\n- **Conscious:** 15-20g fast-acting glucose (juice, glucose tablets)\n- Recheck in 15 minutes, repeat if still low\n- Follow with complex carbohydrate snack\n- **Unconscious:** IV dextrose 50% (50mL) or IM glucagon 1mg\n- Do NOT give oral glucose to unconscious patient\n\n⚠️ **Recurrent hypoglycemia → review insulin/sulfonylurea dose**', 'en', 'ADA/BNF', 10, true),

('red_flags', 'acute_asthma', ARRAY['asthma attack','acute asthma','wheeze','breathless','peak flow','nebulizer','status asthmaticus','bronchospasm'], 'Acute Severe Asthma', E'## Acute Severe Asthma Red Flags\n\n**Moderate exacerbation:**\n- PEF 50-75% best/predicted\n- Increasing symptoms, no life-threatening features\n\n**Severe:**\n- PEF 33-50%, RR ≥25, HR ≥110\n- Cannot complete sentences\n\n**Life-threatening:**\n- PEF <33%, SpO2 <92%, silent chest\n- Cyanosis, bradycardia, hypotension\n- Exhaustion, confusion, coma\n\n**Immediate action:**\n- High-flow oxygen (target SpO2 94-98%)\n- Salbutamol nebulizer 5mg (repeat every 20 min)\n- Ipratropium 500mcg nebulizer\n- Prednisolone 40-50mg oral or IV hydrocortisone 100mg\n- IV magnesium sulfate 2g if life-threatening\n\n⚠️ **Silent chest = near-fatal — prepare for intubation**', 'en', 'BTS/NICE', 10, true),

('red_flags', 'testicular_torsion', ARRAY['testicular torsion','testicular pain','scrotal pain','swollen testicle','absent cremasteric reflex','acute scrotum'], 'Testicular Torsion', E'## Testicular Torsion Red Flags\n\n**Suspect if:**\n- Sudden onset severe testicular pain\n- Nausea and vomiting\n- High-riding testicle\n- Absent cremasteric reflex\n- Swollen, tender hemiscrotum\n\n**Key points:**\n- Peak age: 12-18 years\n- 6-hour window for surgical salvage\n- Do NOT wait for imaging if clinical suspicion high\n\n**Immediate action:**\n- Urgent surgical exploration\n- Manual detorsion attempt (''open the book'' — medial to lateral)\n- Bilateral orchidopexy if torsion confirmed\n\n⚠️ **>6 hours = high risk of testicular loss — TIME IS TESTICLE**', 'en', 'Urology/EAU', 10, true),

('red_flags', 'placental_abruption', ARRAY['placental abruption','antepartum hemorrhage','vaginal bleeding pregnancy','abdominal pain pregnancy','uterine tenderness','fetal distress'], 'Placental Abruption', E'## Placental Abruption Red Flags\n\n**Suspect if:**\n- Painful vaginal bleeding in late pregnancy\n- Woody-hard, tender uterus\n- Fetal distress or absent fetal heart\n- Maternal shock disproportionate to visible bleeding\n\n**Risk factors:**\n- Hypertension, pre-eclampsia\n- Previous abruption, trauma\n- Cocaine use, smoking\n\n**Immediate action:**\n- Large bore IV access x2\n- Crossmatch 4-6 units\n- Continuous CTG monitoring\n- Urgent obstetric review\n- Emergency cesarean if fetal distress\n\n⚠️ **Concealed abruption — minimal visible bleeding but severe shock**', 'en', 'RCOG/WHO', 10, true),

('red_flags', 'acute_glaucoma', ARRAY['acute glaucoma','eye pain','red eye','halos','vision loss','fixed dilated pupil','raised iop','intraocular pressure'], 'Acute Angle-Closure Glaucoma', E'## Acute Angle-Closure Glaucoma Red Flags\n\n**Suspect if:**\n- Sudden severe eye pain\n- Blurred vision with halos around lights\n- Red eye with fixed, mid-dilated pupil\n- Nausea, vomiting, headache\n- Rock-hard eye on palpation\n\n**Risk factors:**\n- Hyperopia (long-sighted)\n- Age >60, female\n- Asian ethnicity\n- Dim lighting, certain medications (anticholinergics)\n\n**Immediate action:**\n- Topical pilocarpine 2% (constrict pupil)\n- Topical timolol 0.5%\n- IV acetazolamide 500mg\n- Urgent ophthalmology referral\n- Definitive: laser peripheral iridotomy\n\n⚠️ **Delay = permanent vision loss within hours**', 'en', 'AAO/NICE', 10, true),

('red_flags', 'aortic_dissection', ARRAY['aortic dissection','tearing chest pain','back pain','blood pressure difference','wide mediastinum','marfan'], 'Aortic Dissection', E'## Aortic Dissection Red Flags\n\n**Suspect if:**\n- Sudden, severe ''tearing'' chest/back pain\n- BP difference >20mmHg between arms\n- Pulse deficit\n- New aortic regurgitation murmur\n- Neurological deficit\n\n**Risk factors:**\n- Hypertension (most common)\n- Marfan syndrome, Ehlers-Danlos\n- Bicuspid aortic valve\n- Cocaine use\n\n**Immediate action:**\n- IV beta-blocker (target HR <60, SBP <120)\n- Pain control (IV morphine)\n- Urgent CT aortogram\n- Type A (ascending) → emergency surgery\n- Type B (descending) → medical management\n\n⚠️ **Mortality increases 1-2% per hour if untreated**', 'en', 'AHA/ESC', 10, true),

('red_flags', 'tension_pneumothorax', ARRAY['tension pneumothorax','pneumothorax','collapsed lung','absent breath sounds','tracheal deviation','chest trauma'], 'Tension Pneumothorax', E'## Tension Pneumothorax Red Flags\n\n**Clinical diagnosis — do NOT wait for CXR:**\n- Respiratory distress, tachycardia\n- Absent breath sounds on affected side\n- Tracheal deviation AWAY from affected side\n- Distended neck veins (JVD)\n- Hypotension, cardiac arrest\n\n**Causes:**\n- Trauma (penetrating/blunt)\n- Mechanical ventilation\n- Spontaneous (tall, thin males)\n- Post-procedure (central line, lung biopsy)\n\n**Immediate action:**\n- Needle decompression: 2nd intercostal space, mid-clavicular line\n- 14G cannula, hear rush of air\n- Follow with chest drain (4th/5th ICS, mid-axillary line)\n\n⚠️ **This is a clinical diagnosis — treating saves lives, waiting for X-ray kills**', 'en', 'ATLS/BTS', 10, true),

('red_flags', 'status_epilepticus', ARRAY['status epilepticus','prolonged seizure','seizure','convulsion','fitting','epilepsy emergency'], 'Status Epilepticus', E'## Status Epilepticus Red Flags\n\n**Definition:** Seizure lasting >5 minutes OR ≥2 seizures without recovery between\n\n**Immediate action (stepwise):**\n1. **0-5 min:** ABC, recovery position, oxygen, check glucose\n2. **5-10 min:** IV lorazepam 4mg (or rectal diazepam 10mg)\n3. **10-20 min:** Repeat benzodiazepine once\n4. **20-40 min:** IV phenytoin 20mg/kg (or levetiracetam)\n5. **>40 min:** RSI and thiopental/propofol infusion (ICU)\n\n**Key points:**\n- Protect airway, turn on side\n- Do NOT restrain or put anything in mouth\n- Check glucose — treat if <4 mmol/L\n- After seizure: postictal care, identify cause\n\n⚠️ **Prolonged seizures cause brain damage — every minute counts**', 'en', 'NICE/AES', 10, true),

('red_flags', 'anaphylaxis', ARRAY['anaphylaxis','allergic reaction','swelling','urticaria','throat swelling','epinephrine','adrenaline','shock'], 'Anaphylaxis', E'## Anaphylaxis Red Flags\n\n**Diagnose if rapid onset (minutes to hours) of:**\n- Airway: swelling, stridor, hoarse voice\n- Breathing: wheeze, dyspnea, SpO2 drop\n- Circulation: hypotension, tachycardia, pale\n- Skin: urticaria, flushing, angioedema\n\n**Immediate action:**\n1. Remove trigger, call for help\n2. **IM Adrenaline (1:1000):**\n   - Adult: 0.5mg (0.5mL) IM anterolateral thigh\n   - Child 6-12y: 0.3mg, <6y: 0.15mg\n3. High-flow oxygen\n4. IV fluid bolus (20mL/kg crystalloid)\n5. Repeat adrenaline every 5 min if no improvement\n6. Chlorphenamine + hydrocortisone (secondary)\n\n⚠️ **Biphasic reaction possible — observe for minimum 6-12 hours**', 'en', 'Resuscitation Council UK', 10, true),

('red_flags', 'sepsis', ARRAY['sepsis','septic shock','infection','fever','tachycardia','hypotension','lactate','qsofa','organ failure'], 'Sepsis', E'## Sepsis Red Flags\n\n**qSOFA criteria (≥2 = suspect sepsis):**\n- RR ≥22/min\n- Altered mentation (GCS <15)\n- SBP ≤100 mmHg\n\n**Sepsis-3 definition:** Life-threatening organ dysfunction caused by dysregulated host response to infection\n\n**SEPSIS SIX (within 1 hour):**\n1. Give high-flow oxygen\n2. Take blood cultures\n3. Give IV antibiotics\n4. Give IV fluid challenge (30mL/kg crystalloid)\n5. Check lactate level\n6. Measure urine output (catheter)\n\n**Red flags for septic shock:**\n- Lactate >2 mmol/L\n- Vasopressors needed to maintain MAP ≥65\n- Persistent hypotension despite fluids\n\n⚠️ **Each hour delay in antibiotics increases mortality by 7.6%**', 'en', 'Surviving Sepsis/NICE', 10, true),

('red_flags', 'stroke', ARRAY['stroke','cva','facial droop','arm weakness','speech','fast','thrombolysis','tpa','cerebrovascular'], 'Acute Stroke', E'## Acute Stroke Red Flags\n\n**FAST screening:**\n- **F**ace: drooping on one side\n- **A**rms: cannot raise both equally\n- **S**peech: slurred or absent\n- **T**ime: call emergency immediately\n\n**Ischemic stroke (85%):**\n- Thrombolysis (IV alteplase) within 4.5 hours of onset\n- Thrombectomy within 6-24 hours if large vessel\n- Aspirin 300mg after CT excludes hemorrhage\n\n**Hemorrhagic stroke (15%):**\n- Reverse anticoagulation urgently\n- BP control (target <140 systolic)\n- Neurosurgical review\n\n**Key points:**\n- Door-to-needle time <60 minutes\n- CT head ASAP (exclude hemorrhage before thrombolysis)\n- Do NOT give aspirin until CT confirmed ischemic\n\n⚠️ **Time is brain — 1.9 million neurons die every minute**', 'en', 'AHA/NICE', 10, true),

('red_flags', 'acute_mi', ARRAY['heart attack','myocardial infarction','mi','stemi','nstemi','chest pain','troponin','ecg changes','cardiac'], 'Acute Myocardial Infarction', E'## Acute MI Red Flags\n\n**Suspect if:**\n- Central crushing chest pain >20 min\n- Radiation to left arm, jaw, back\n- Diaphoresis, nausea, dyspnea\n- Pain not relieved by GTN\n\n**STEMI management:**\n1. Aspirin 300mg chewed\n2. Ticagrelor 180mg or Clopidogrel 300mg\n3. Morphine 5-10mg IV + metoclopramide\n4. GTN sublingual (avoid if SBP <90)\n5. Primary PCI within 120 min (preferred)\n6. Thrombolysis if PCI not available within 120 min\n\n**NSTEMI management:**\n- GRACE score for risk stratification\n- Fondaparinux or LMWH\n- Angiography within 72 hours if high risk\n\n⚠️ **Silent MI common in diabetics and elderly — low threshold for ECG**', 'en', 'AHA/ESC/NICE', 10, true),

('red_flags', 'cord_prolapse', ARRAY['cord prolapse','umbilical cord','fetal distress','labor emergency','presenting cord','obstetric emergency'], 'Umbilical Cord Prolapse', E'## Cord Prolapse Red Flags\n\n**Suspect if:**\n- Cord felt on vaginal exam\n- Cord visible at introitus\n- Sudden severe fetal bradycardia after membrane rupture\n\n**Risk factors:**\n- Polyhydramnios, preterm\n- Malpresentation (transverse, breech)\n- Artificial rupture of membranes\n\n**Immediate action:**\n1. Call for help — emergency cesarean\n2. Fill bladder with 500mL saline (retrograde catheter)\n3. Position: knee-chest or Trendelenburg\n4. Manually elevate presenting part (hand in vagina)\n5. Do NOT attempt to replace the cord\n6. Keep cord warm and moist if exposed\n7. Tocolysis (terbutaline 0.25mg SC) to stop contractions\n\n⚠️ **Delivery within minutes — fetal death if compression sustained**', 'en', 'RCOG/WHO', 10, true);
