// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxafzwlodzohrwdwkuzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4YWZ6d2xvZHpvaHJ3ZHdrdXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3NjY5NDgsImV4cCI6MjA4MzM0Mjk0OH0.KPwz8hT-p5dHVRKOvdU582ENu5vay734Gz4GVs5sCCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
